### ISSUE TITLE
Could not deduce type in main.cpp for efficientnet

### ISSUE THREAD

**Issue by Lokwill** [serizba/cppflow#103]
Hello,

Running main.cpp for efficientnet throws this error on the line that uses the cppflow::arg_max(output,1). What could be the cause here? 

"terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not deduce type!
Aborted (core dumped)"

I put the executable through the debugger and if fails after this instruction:__builtin_memmove(__result, __first, sizeof(_Tp) * _Num); in /usr/include/c++/9/bits/stl_algobase.h. 

I ran the create_model.py script in Google Colab and then downloaded the model, since there isn't a model in the examples directory already generated.

Thanks!

**Comment by Lokwill** [comment]
Yes, I didn't change anything in the code for main.cpp

And this is what I used to create the model: 
```
import tensorflow as tf
model = tf.keras.applications.EfficientNetB0()

# Export the model to a SavedModel
model.save('model', save_format='tf')
```

I tried printing content of output and got the same error of 
"terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not deduce type!
Aborted (core dumped)"

When I ran it through the debugger, I saw it failed at TF_DataType deduce_tf_type() in cppflow/datatype.h and threw the Could not deduce type error.

**Comment by CreatorSky** [comment]
I am facing the similar issue whenever I use cppflow::cast().

**Comment by serizba** [comment]
Hi @Lokwill ,

Have you tried if small pieces of code work for you? Without loading a model. Just create some tensors and print them.

**Comment by Lokwill** [comment]
So, I just tried this, and it still threw the same error for not being able to deduce the type, and at the same place in the debugger. This is the code I used.
```
        auto input = cppflow::fill({1,1,1,3}, 1.0f);
        std::cout <<"Before loading model\n";
        cppflow::model model("../model");
        std::cout <<"Before inference\n";
        auto output = model({{"serving_default_input_1:0", input}},{"StatefulPartitionedCall:0"});
        std::cout <<"See the output layer\n";

        std::cout << "Content of output:" << output << std::endl;

        return 0;
```

**Comment by serizba** [comment]
I mean without loading a model and running it. Just create a tensor and print it to see if it works.

```C++
auto test = cppflow::fill({1,1,1,3}, 1.0f);
std::cout << test << std::endl;
```

**Comment by Lokwill** [comment]
Ah, yes. That works fine, and this is what is the output:

(tensor: shape=[1 1 1 6], data=
[[[[1 1 1 1 1 1]]]])

**Comment by ljn917** [comment]
@Lokwill Can you try #106 and see what is the output?

**Comment by Lokwill** [comment]
After #106, this is the output:

terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not deduce type! type_name: St6vectorIN7cppflow6tensorESaIS1_EE
Aborted (core dumped)

**Comment by ljn917** [comment]
`cppflow::model::operator()` returns `std::vector<cppflow::tensor>`. You will need to use `output[0]`, `output[1]`, ... to access the results.

FYI
```
$ c++filt --type St6vectorIN7cppflow6tensorESaIS1_EE
std::vector<cppflow::tensor, std::allocator<cppflow::tensor> >
```

**Comment by Lokwill** [comment]
Aha, I see.

How would I adjust this line in the main.cpp in the efficientnet to see the prediction?
```
 std::cout << "It's a tiger cat: " << cppflow::arg_max(output, 1) << std::endl;

```
Would it just be a matter of altering output to output[0]? When I do that, my output becomes:
(tensor: shape=[1], data=[283])
But, I'm not too sure how to evaluate that?

**Comment by ljn917** [comment]
Adding correct indexing to variable `output`, e.g. `output[0]`, should be
sufficient. Here is an example,
https://serizba.github.io/cppflow/examples.html#multiinputoutput

**Comment by Lokwill** [comment]
Cool, thanks, @ljn917 and @serizba, it works fine now!

As a final question, should main.cpp be altered to reflect that change of output[0] instead of output?

**Comment by ljn917** [comment]
Which main.cpp are you referring to?

**Comment by Lokwill** [comment]
This one: cppflow/examples/efficientnet/main.cpp

**Comment by ljn917** [comment]
No, the original version can be run without problem.

**Comment by Lokwill** [comment]
Ah, I see. Hope it doesn't cause any problems down the line. Thanks again!
