### ISSUE TITLE
Error: No operation named "init" exists

### ISSUE THREAD

**Issue by du-david** [serizba/cppflow#11]
Hello serizba,

I succeeded with compiling the examples, but when testing on my own model, I ran into an error at the line of model construction, Model model(model_file):
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: No operation named "init" exists
Aborted (core dumped)
Do you know why?

My model was converted from pytorch to tensorflow using onnx and I can load it in python. The following are the codes for testing:
int main() {
    Model model("../mymodel.pb");
    model.init();

    auto input = new Tensor(model, "prefix/input_batch");
    auto output_a  = new Tensor(model, "prefix/output_c");
    auto output_b  = new Tensor(model, "prefix/output_v");

    std::vector<float> img(1*3*361*641);
    std::iota(img.begin(), img.end(), 0);
    input->set_data(img, {1, 3, 361, 641});

    model.run(input, {output_a, output_b});
    for (float f : output_a->get_data<float>()) {
        std::cout << f << " ";
    }
    std::cout << std::endl;

}

**Comment by Brimill** [comment]
I running into the same issue :/ The examples work fine, but model.init() fails with the model I need to run.

**Comment by serizba** [comment]
When calling model.init(), the model is looking for an operation called "init" to initialize the variables. When using code similar to the examples (basic tensorflow) the operation to initialize the variables is always called "init". Nevertheless by converting your graph from PyTorch it may not be the case. 

I would look for the name of the operation that initialize the variables, you can list all the available operations by model.get_operations(). If you find it you can replace in your Model.cpp code the name "init" by your new operation.

Hope it works

**Comment by du-david** [comment]
Thanks for the reply.
