### ISSUE TITLE
How to create a tensor from a 2D std::vector?

### ISSUE THREAD

**Issue by andrew-zaborenko** [serizba/cppflow#114]
Hi!
Thanks for all the work you've put in this project -- it's an amazing way of doing inference in a C++ environment. 
I was wondering if there is a way of creating tensors with multiple dimensions.

CppFlow works great with 1D tensors:

```
int X_dim = 1024;
std::vector<double> values(X_dim);
std::vector<int64_t> shape (1);

shape[0] = X_dim;
tensor = cppflow::tensor(values, shape);
```
This code creates a tensor with shape=[1024] as expected.

However, if I try to create a 2D tensor:

```
int X_dim = 1024;
int Y_dim = 2;
std::vector<double> values(X_dim, Y_dim);
std::vector<int64_t> shape (2);

shape[0] = X_dim;
shape[1] = Y_dim;
tensor = cppflow::tensor(values, shape);
```
I get a segmentation error. 
Is there a way of creating a tensor with shape=[1024, 2]?

P.S. I've tried concatenating two 1D tensors into one 2D tensor using _concat_ operation from  _raw_ops.h_ file but couldn't fully understand this function.

**Comment by serizba** [comment]
Hi @andrew-zaborenko 

The way you are initializing the `std::vector` is not doing what you expect. You are actually creating a 1D vector of size X_dim initialized with 2s (`std::vector(size_type count, const T& value`).

If you want to provide a 2D tensor to cppflow you have to create a flat vector and create a tensor specifying the size:
```C++
// Creates a X_dim * Y_dim size vector filled with zeroes
std::vector<double> values(X_dim * Y_dim, 0.0);

// Creates a tensor from the vector with shape [X_dim, Y_dim]
tensor = cppflow::tensor(values, {X_dim, Y_dim});
```

Hope it helps!

**Comment by andrew-zaborenko** [comment]
Hi @serizba
Thank you for your help and a quick reply! Your answer has solved my issue.

**Comment by alfanrizaldy** [comment]
hey @andrew-zaborenko 
could you fill vector values with custom value i.e from another vector? i've already asked here for detail https://github.com/serizba/cppflow/issues/187 , please inform me if you know how to do that
thank you
