### ISSUE TITLE
libtensorflow2 (or cppflow) should be updated ?

### ISSUE THREAD

**Issue by flaviu22** [serizba/cppflow#119]
I have tried to compile your excellent library, cppflow.

I am using Win10, 64 bit, VS2017.

I have downloaded https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.4.0.zip and I have deployed on my HOME folder: `C:\Users\u724776\libtensorflow2`

And I have tried to compile cppflow, but I got: 

```
1>------ Build started: Project: example, Configuration: Debug x64 ------
1>cl : Command line warning D9002: ignoring unknown option '-fno-omit-frame-pointer'
1>cl : Command line warning D9002: ignoring unknown option '-fsanitize=address'
1>main.cpp
1>C:\Users\u724776\libtensorflow2\include\tensorflow/c/tf_tensor.h(22): fatal error C1083: Cannot open include file: 'tensorflow/c/c_api_macros.h': No such file or directory
1>Done building project "example.vcxproj" -- FAILED.
2>------ Skipped Build: Project: ALL_BUILD, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========

```
which tell me that `cppflow` is not fit with `libtensorflow2`, am I right ?

![image](https://user-images.githubusercontent.com/37621568/117585498-66b05e80-b11b-11eb-9ed5-75b9c29fe3a3.png)

**Comment by seungtaek94** [comment]
@flaviu22 

I think that is tensroflow [issue](https://github.com/tensorflow/tensorflow/issues/46343#issuecomment-758635275)

U can download linux version and copy header file to ur windows tf c_api folder.

**Comment by flaviu22** [comment]
I have make it to run by using `libtensorflow-gpu-windows-x86_64-2.5.0`.
