### ISSUE TITLE
data buffer desallocation

### ISSUE THREAD

**Issue by dbrazey** [serizba/cppflow#12]
Hello, 

In the class Tensor.cpp, the buffer "data" is allocated with "malloc" and then given to "TF_NewTensor" with a custom deleter. This deleter uses "delete[]" to desallocate the buffer. 

Should we use "free" instead of "delete []" ? 
Am I wrong ? 

Thanks

**Comment by serizba** [comment]
Hi!

Thanks for your hint. Some collaborators have improved the memory management of the project and changed the deleted by a free some time ago. If you detect more issue of this kind, please open a new issue :blush: 

I proceed to close the issue.

Thanks
