### ISSUE TITLE
Loading model for real-time audio application

### ISSUE THREAD

**Issue by raphael-09** [serizba/cppflow#122]
Hi all,

I am sorry if my post is not appropiate to the Issues content, but I didnt know where to post else.
Like the title says, I try to implement a tensorflow model to process an audio stream inside my realtime audio application made with JUCE6. 
The problem is that I cannot declare the model inside the loop function which is called 44k times per second, CPU overflows and the app crashes. I want to instantiate the model once, saving it to a variable? and then use it inside my process() method.

How could I achieve that?

Placing the model load inside my prepare() method doesnt work either because I cannot access the model from my process() method then.

My header file has the following structure:
```
class Filter
{
  public:
  Filter();
  void prepare(const juce::dsp::ProcessSpec& spec);
  void process(const ProcessContext& context) noexcept
  {
    const auto& inputBlock = context.getInputBlock();
    auto& outputBlock = context.getOutputBlock();
    const auto numChannels = outputBlock.getNumChannels();
    const auto numSamples = outputBlock.getNumSamples();

    jassert(inputBlock.getNumChannels() == numChannels);
    jassert(inputBlock.getNumSamples() == numSamples);

    if (context.isBypassed)
    {
        outputBlock.copyFrom(inputBlock);
        return;
    }

    for (size_t channel = 0; channel < numChannels; ++channel)
    {
        auto* inputSamples = inputBlock.getChannelPointer(channel);
        auto* outputSamples = outputBlock.getChannelPointer(channel);

        auto input = cppflow::fill({128, 128,1}, 1.0f); // dummy data;

        //auto output = model(input); // Not working if referenced here
    }
  }
  
  private:
  double sampleRate = 44100.0;
  // cppflow::model model; // Something like that possible?
}
```

**Comment by raphael-09** [comment]
I created a pointer inside the private:
`cppflow::model *model;`

Inside my prepare() method I instantiate the model like so:
`model = new cppflow::model("<Path_to_model>");`

And finally inside the process method I try to predict like so:
`auto output = model->operator()(input);`

Which leads to a std::runtime_error and abort() is being called.

**Comment by serizba** [comment]
Hi @raphael-09 

What does the std::runtime_error say?

**Comment by raphael-09** [comment]
Hi @serizba 

The Debugger detects memory leaks probably caused by the "new" statement in order to load the model.

**Comment by serizba** [comment]
But what is the error message?

And in which line does it fail?

**Comment by raphael-09** [comment]
The error message is: "abort() has been called" Line 28 inside the report_runtime_error.cpp

When only initializing the model and not passing any data to it, it does not crash.

**Comment by raphael-09** [comment]
@serizba were you able to trace down the issue?

**Comment by serizba** [comment]
Hi @raphael-09 

No, I don't have enough information.

Perhaps you are feeding the model with a tensor of incorrect type or dimension, that's why the "TF_INVALID_ARGUMENT.". Usually, when the program aborts on the `status_check` an informative error message is thrown. I don't know why you are not able to see it. 

For instance, if I feed a model with a tensor of the wrong type I obtain this:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Expects arg[0] to be float but double is provided
Aborted (core dumped)
```
Do you get something similar?

**Comment by raphael-09** [comment]
Hi Serizba,

The dimensions match. I trained the model with an input size of (128,128,1). Even if I pass a tensor with the wrong size, I get the same error message as with the correct input size.
I also checked if I do not pass the correct type into the model.
In Python, 
`print(type(X_in[0][0]))` returns:
 <class 'numpy.ndarray'>.
`print(X_in)` returns: 
[[[[ 0.80156406]
   [ 0.74624233]
   [-0.01342476]
   ...

Filling the input tensor with: 
`auto input = cppflow::fill({128, 128, 1}, 1.0f); // stft_audio to tensor`
should be correct then.

The Error meesage is:
_______________________________________________________________________________________________________________
Exception thrown at 0x00007FF8A6163B19 in VoiceCleaning.exe: Microsoft C++ exception: std::runtime_error at location 0x0000000EBDDFE528.
Debug Error!

Program: ...VoiceCleaning\VoiceCleaning_artefacts\Debug\VoiceCleaning.exe

abort() has been called

(Press Retry to debug the application)
_______________________________________________________________________________________________________________

When I click on Retry, like the Error message suggests, I get directed to line 28 in report_runtime_error.cpp. This line triggers _CrtDbgBreak();
When continuing with the Debugging, i get the following messages under the initial error message:


_______________________________________________________________________________________________________________
VoiceCleaning.exe hat einen Haltepunkt ausgelöst.

Detected memory leaks!
Dumping objects ->
{52641} normal block at 0x0000025330DE18C0, 152 bytes long.
 Data: <  -1S      ?    > B0 18 2D 31 53 02 00 00 00 00 80 3F 00 00 00 00 
{52640} normal block at 0x000002532E5E25D0, 128 bytes long.
 Data: <+       F       > 2B 00 00 00 00 00 00 00 46 01 00 00 BD 00 00 00 
{52639} normal block at 0x00000253312D18B0, 32 bytes long.
 Data: <   0            > 98 F0 F2 30 F6 7F 00 00 02 00 00 00 00 00 00 00 
{52638} normal block at 0x0000025330DE19A0, 152 bytes long.
 Data: <  -1S      ?    > 90 1A 2D 31 53 02 00 00 00 00 80 3F 00 00 00 00 
{52637} normal block at 0x000002532E5E4190, 128 bytes long.
 Data: <        q       > 00 00 00 00 00 00 00 00 71 01 00 00 BD 00 00 00 
.
.
.
_______________________________________________________________________________________________________________

**Comment by raphael-09** [comment]
> `print(X_in)` returns:
> [[[[ 0.80156406]
> [ 0.74624233]
> [-0.01342476]
> ...
> 
> Filling the input tensor with:
> `auto input = cppflow::fill({128, 128, 1}, 1.0f); // stft_audio to tensor`
> should be correct then.
> 

But it was not correct. @serizba you where right. Looking at the X_in output there are three starting brackets [[[ [value][value] ... Meaning The shape should start with 3. Printing the shape of X_in would have pointed me to that issue directly...

Adjusted the cppfill to` auto input = cppflow::fill({3, 128, 128, 1}, 1.0f); // stft_audio to tensor` and my app is not crashing anymore.

I am sorry if I have wasted your time.

Thanks for your help and all the best!
Raphael
