### ISSUE TITLE
Model path language issue.

### ISSUE THREAD

**Issue by seungtaek94** [serizba/cppflow#123]
Hi. 

If model path include korean. It cause error(Cant load the model).

**Comment by serizba** [comment]
Hi @seungtaek94 

You mean if the model directory in the filesystem includes Korean? I tried this in my computer (Linux) and it works:
```c++
cppflow::model model("../파일 이름");
```

I don't know if that's your issue. 

Anyway, it shouldn't be a problem to change your model name as a workaround right?

**Comment by seungtaek94** [comment]
Hi, @serizba 

Yep, that translated filename is correct :)

korean path deosnt work for me when i using `Saved Model` on  windows system with visual studio 2019. (I will try more)

But know i using only `frozen.pb` file with custom model loader. It can handle korean path :)

**Comment by serizba** [comment]
Hi @seungtaek94 

Sorry for not replying before. But this looks like a problem with windows and not related with cppflow.
