### ISSUE TITLE
Convert cppflow::arg_max(output, 1) to string ? or get only ID to string?

### ISSUE THREAD

**Issue by Gert186d** [serizba/cppflow#125]
Hi Can somebody tell me how to convert cppflow::arg_max(output, 1) to string in C++ ???

**Comment by serizba** [comment]
Hi @Gert186d 

I don't know exactly what you mean. If you just want to convert your tensor to a string, you can just do `cppflow::to_string(cppflow::arg_max(output, 1))`

**Comment by Gert186d** [comment]
Thanks that was my question 
So nice work 

Mit freundlichen Grüßen 
Dr. Gert Taucher
