### ISSUE TITLE
cppflow::get_context(), get_global_context() have issue when use specific GPU.

### ISSUE THREAD

**Issue by seungtaek94** [serizba/cppflow#126]
Hi.

I generate serialized option with `config.gpu_options.visible_device_list = '1'`  then i got `{0x32,0xc,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xa9,0x3f,0x2a,0x1,0x31,0x38,0x1}`.

Full options:
```
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.05
config.gpu_options.allow_growth = False
config.allow_soft_placement = True 
config.gpu_options.visible_device_list = '0'
```

And i set gloabal context like below:
```
std::vector<uint8_t> config{0x32,0xc,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xa9,0x3f,0x2a,0x1,0x31,0x38,0x1};

TFE_ContextOptions* options = TFE_NewContextOptions();
TFE_ContextOptionsSetConfig(options, config.data(), config.size(), cppflow::context::get_status());

cppflow::get_global_context() = cppflow::context(options);
```

---
When we call below function;
```
cppflow::get_global_context() = cppflow::context(options);
```

`cppflow::context(options)` functions go to below line. And it successfully initialized new context with my serialized GPU options.
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/context.h#L71
TF log output:
```
2021-05-28 14:12:43.387591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 1
2021-05-28 14:12:44.019801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 14:12:44.604777: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      1
2021-05-28 14:12:44.605025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N
```

---
After then `cppflow::get_global_context()` go to below line. And it initialized the context with `TFE_NewContextOptions()`.
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/context.h#L68

TF log output:
```
2021-05-28 14:13:00.877082: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1
2021-05-28 14:13:01.248817: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 14:13:01.249277: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1
2021-05-28 14:13:01.250173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N N
2021-05-28 14:13:01.251008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N N
```
---

When we call `cppflow::get_global_context()`, it try to  reallocate the context with `TFE_NewContextOptions()`. 
So it ignore my options that set by `cppflow::context(options)'.

This problem occurs every time when `cppflow::get_global_context()` is called.

Im not sure people who read this issue can understand because of my poor English skills :(

**Comment by ljn917** [comment]
Can you attach minimum runnable code which can reproduce the issue?

**Comment by ljn917** [comment]
In addition, if you load a model, is it loaded into both GPUs or just GPU
#1?

**Comment by seungtaek94** [comment]
@ljn917 

It cause error at below line when cpp::get_global_context() is called.  So model cannot loaded. 

https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/context.h#L73


```
#include "cppflow/cppflow.h"
#include <iostream>

int main()
{
    std::vector < uint8_t> vecSerializedGPULimit = { 0x32,0xc,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xa9,0x3f,0x2a,0x1,0x31,0x38,0x1 };
    TFE_ContextOptions* options = TFE_NewContextOptions();
    TFE_ContextOptionsSetConfig(options, vecSerializedGPULimit.data(), vecSerializedGPULimit.size(), cppflow::context::get_status());

   cppflow::get_global_context() = cppflow::context(options);

    return 0;
}
```

**Comment by ljn917** [comment]
Is it working if you do not change cppflow::get_global_context() but set
CUDA_VISIBLE_DEVICES=1 instead?

**Comment by seungtaek94** [comment]
@ljn917 

Yes if i set "CUDA_VISIBLE_DEVICES=1" it works.

But i cant use that environment variable for this work. 

Because other object which is in same project also use GPU.

**Comment by ljn917** [comment]
@seungtaek94 It seems I cannot reproduce your issue. I don't have a dual card system, but setting a new context on device 0 and replacing the default context works fine on my laptop. Please see the comments in the code for changes.

This is tested with TF C lib 2.5, cuda 11.3, and kernel 5.12.7. 

```
// Modified examples/load_model/main.cpp
// Note: Need to switch off debugging in cmake

#include <iostream>

#include "cppflow/ops.h"
#include "cppflow/model.h"


int main() {
    // changed your config 0x31 to 0x30 to place on device 0
    std::vector<uint8_t> config{0x32,0xc,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xa9,0x3f,0x2a,0x1,0x30,0x38,0x1};
    std::unique_ptr<TFE_ContextOptions, decltype(&TFE_DeleteContextOptions)> options(TFE_NewContextOptions(), &TFE_DeleteContextOptions);
    TFE_ContextOptionsSetConfig(options.get(), config.data(), config.size(), cppflow::context::get_status());
    cppflow::status_check(cppflow::context::get_status());

    // Two TFE_Context objects are created here, but the program should proceed without error.
    // The default TFE_Context (device 0 on my machine) is allocated and then deallocated.
    // The new TFE_Context should be kept.
    cppflow::get_global_context() = cppflow::context(options.get());
    
    auto input = cppflow::fill({10, 5}, 1.0f);
    cppflow::model model("../model");
    auto output = model(input);
    
    std::cout << output << std::endl;

    auto values = output.get_data<float>();

    for (auto v : values) {
        std::cout << v << std::endl;
    }
    return 0;
}
```

**Comment by seungtaek94** [comment]
@ljn917 

Before i tested it with win10, TF 2.4.0, cuda 11.2, rtx 2080 super * 2, 
and i just tested it with ubuntu18.04, TF 2.4.0, cuda 11.2, titan xp * 4 but both systems are occur same issue.

when i use device 0 like ur comments it doesnt throw error. but if i use other devices(no device 0) it cause error.

If i set global_context for use specific gpu device 1~n, `cppflow::context(options.get())` successfully allocate, but when called `cppflow::get_global_context()` and `session_options` in `cppflow::model::model()`these are tried to allocate every device.


`cppflow::context(options.get())` log;
![image](https://user-images.githubusercontent.com/56434476/120125487-fd8caa00-c1f3-11eb-9ce6-d8a0ae8a3a7c.png)

`cppflow::get_global_context()` log;
![image](https://user-images.githubusercontent.com/56434476/120125524-257c0d80-c1f4-11eb-9aef-bca9f7306e7e.png)


Im not sure which are problem.(maybe it cause by GPU memory access).

I will test more for give u to more information.

And if u someone has multiple  device pls test below. Thanks

https://github.com/serizba/cppflow/issues/126#issuecomment-850174145

**Comment by ljn917** [comment]
The default context uses all devices. The log you showed for
cppflow::get_global_context()
is expected as long as your model can run on the correct device. In fact,
my code shows allocating contexts on device 0 twice.

**Comment by ljn917** [comment]
Okay, I know what is going on here. The model class does not use the global context... because model class is using the graph API, not the eager execution API. The best way may be to overload the constructor like in cppflow v1. What's your opinion, @serizba ?

**Comment by seungtaek94** [comment]
@ljn917 

`context` class also has problem it cant handle multi device.

I changed `cppflow::get_global_context()` like below to use device 1(Also i changed model class to use device 1);

And it works..

```c++
inline context& get_global_context() {
        std::vector < uint8_t> vecSerializedGPULimit = { 0x32,0xc,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xa9,0x3f,0x2a,0x1,0x31,0x38,0x1 };
        TFE_ContextOptions* options = TFE_NewContextOptions();
        TFE_ContextOptionsSetConfig(options, vecSerializedGPULimit.data(), vecSerializedGPULimit.size(), cppflow::context::get_status());

        static context global_context(options);
        return global_context;
 }
```

When called  `cppflow::get_global_context()`,  `opts` will be `nullptr` so  `static context global_context`  initialize with `TFE_NewContextOptions`. And it throws error at `status_check(tf_status)`.
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/context.h#L67

I dont know why that parts occur error only when we use specific device(not zero).

**Comment by ljn917** [comment]
Does TF print any error when status_check(tf_status) fails? This is
unexpected.

It is a temporary workaround. For the longer term, a context manager is
likely needed.

**Comment by seungtaek94** [comment]
@ljn917 

Here is TF error message.
```
TensorFlow device (GPU:0) is being mapped to multiple CUDA devices (0 now, and 1 previously), which is not supported. This may be the result of providing different GPU configurations (ConfigProto.gpu_options, for example different visible_device_list) when creating multiple Sessions in the same process. This is not  currently supported, see https://github.com/tensorflow/tensorflow/issues/19083
```

**Comment by ljn917** [comment]
Just went through the issue. It is more complicated than I thought. I need
some time to think about it.

In short, our current context re-allocation for remapping devices breaks TF
thread safety and internal device naming. We need a context manager to
enforce the thread safety and only allow people to create context once.

Sorry about the inconvenience.

**Comment by ljn917** [comment]
@seungtaek94 Can you test #127 ?
