### ISSUE TITLE
Does it support tf 2.0?

### ISSUE THREAD

**Issue by oak-tree** [serizba/cppflow#13]

**Comment by serizba** [comment]
CppFlow uses Tensorflow C API, and at the moment, the C API does not support officially TensorFlow 2.0

From TensorFlow C API [webpage](https://www.tensorflow.org/install/lang_c):

> Note: There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release.

**Comment by shawnrosofsky** [comment]
Actually, it does support tf 2.0 keras models.  I was able to do this for the mnist example and got it to work. However, you need to convert the models to a concrete function.  Then, convert the concrete function to a frozen graph.  See https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py for an example of how to do this.
