### ISSUE TITLE
Is frozen graph .pb still supported?

### ISSUE THREAD

**Issue by vincent911001** [serizba/cppflow#130]
Hi,

Is the latest cppflow support frozen graph in .pb?

Thanks,
Vincent

**Comment by liyingyinsimon** [comment]
I am also having some problems on using .pb. I have a .pb file from [hed_graph.pb](https://github.com/fengjian0106/hed-tutorial-for-document-scanning/tree/master/checkpoint). I am not sure if the .pb file is also a frozen graph. But I have errors when importing this model. Anyone knows how to solve it?
Thank you!

**Comment by dskkato** [comment]
Currently. there is no method to load `frozen_graph`. [Older cppflow](https://github.com/serizba/cppflow/tree/243ff2fc4e33632b91676cad7d6cfc3c92308601) directly supports the format so you can try it if calling the model prediction step is sufficient.

**Comment by serizba** [comment]
Now is supported, thanks to #152
