### ISSUE TITLE
AVX2 warning?

### ISSUE THREAD

**Issue by logixworx** [serizba/cppflow#139]
When I run the example I get:

This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Should I be concerned? The version of libtensorflow that I downloaded was as instructed on https://www.tensorflow.org/install/lang_c:

Windows CPU only | https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.5.0.zip

**Comment by serizba** [comment]
Hi @logixworx 

No, you shouldn't be concerned. The provided binaries are compiled for generic architectures and therefore they don't use all optimizations that your cpu offers. Unless you are worried on performance you shouldn't be worried. If you want to use all your cpu operations then you will need to compile the tensorflow library yourself.
