### ISSUE TITLE
get different prediction result between cppflow(tf c_api) and keras(python)

### ISSUE THREAD

**Issue by lircsszz** [serizba/cppflow#14]
Hi recently I use cppflow to load model, witch is already transform into .pb form(used to be .h5 form), , and predict with this model(just simple two classes problem).
The model load is successful done, but when using it predicts resluts, I got different result compare with the original model in python？ Do you have any idea why this may happened?

**Comment by serizba** [comment]
Hi!

Could you provide a concrete example of such case? With the provided description I am not able to reproduce your problem, and therefore I cannot manage to solve it

Thanks!

**Comment by serizba** [comment]
Hi!

I hope you solved it. I will proceed to close the issue due to lack of activity.
