### ISSUE TITLE
Comparisons of variables with mismatch in signedness in model.h

### ISSUE THREAD

**Issue by gth828r** [serizba/cppflow#142]
Hello, and thanks for the excellent work on cppflow!

In `model.h` there are a few spots where there are signed and unsigned variables being compared. I am integrating cppflow into a build which is configured to error out on compiler warnings, meaning that I need to fix these up before I can complete my build. Below are the locations where this error is occurring:

https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/model.h#L119
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/model.h#L127
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/model.h#L143
https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/model.h#L162

While this is not urgent, these minor issues should probably be fixed.

**Comment by serizba** [comment]
@gth828r 

Thanks for pointing this. If you changed it feel free to open a PR.

**Comment by gth828r** [comment]
I won't be around today, but I should be able to submit a PR early next week. Thanks for the nudge!

**Comment by serizba** [comment]
Fixed with #180
