### ISSUE TITLE
Problem loading tflite model

### ISSUE THREAD

**Issue by aabilityuk** [serizba/cppflow#146]
Hi dear developer! Just recently start to work with your lib, thank you for a great job!!! Could you please let me know is it possible to load tflite models with your lib? If not so maybe you can give me a hand with how to create and train model in saved_model format? I am trying to make a programm detecting covid face masks with tensorflow.

Here i created a post with information on how i could be able to run some code example with tflite model, but fps is very low and i need more powerful solution, and one of the guys who helped me with my question adviced to ask you about any other help conserning the cppflow/

Here is the original post: https://discuss.tensorflow.org/t/very-low-fps-in-tensorflow-lite-example-on-windows-10/3866

**Comment by serizba** [comment]
To create and train a saved format model you can take a look to the examples, or you could check the official docs of tensorflow.
