### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by tkschmidt** [serizba/cppflow#15]
Hi, serizba :)
a very nice project of yours, finally a nice way to use the Tensorflow API. Using Keras/Tensorflow serving I'm used to do batch interference. I was wondering if it is possible to do multiple inference also with your code.

Is **set_data** with a shape as a second argument the correct path for me to find the solution?
```
    int predictions = 2;
    std::vector<int32_t> data_a(predictions * 24);
    std::iota(data_a.begin(), data_a.end(), 1);
   #data_a.resize(24 * predictions);


    std::vector<float> data_b(predictions * 3);
    std::iota(data_b.begin(), data_b.end(), 1);
    #data_b.resize(3* predictions);


    const std::vector<std::int64_t> data_a_shape = { predictions,24};
    const std::vector<std::int64_t> data_b_shape = { predictions, 3 }

	input_a->set_data(data_a, data_a_shape);
	input_b->set_data(data_b, data_b_shape);


	m.run({ input_a, input_b }, output);
```

Just to add some extra information.
Example network has to input parameters A with 24 parameters and B with 3 parameters.
for `prediction=1` it works fine

**Comment by serizba** [comment]
Hi!

Sorry to answer so late. I am sorry, but I am not sure what do you mean with multiple inference. Could you explain a bit more what do you want to achieve?

Thanks

**Comment by serizba** [comment]
I proceed to close the issue due to lack of activity
