### ISSUE TITLE
Cppflow runs slow after a time

### ISSUE THREAD

**Issue by Gert186d** [serizba/cppflow#161]
Hi, 
I noticed that Cppflow runs slower after a certain of time. 
I initialize the model ones and feed it in a loop with pictures. 
works well. 

I feed it with 
auto input 
And 
auto output 

works fine for about 3-4 hour’s than it becomes slow. 
should I free the variable somewhere?

**Comment by serizba** [comment]
I haven't heard of this kind of issue before. Are you continuously creating new tensors?

**Comment by Gert186d** [comment]
Sorry, 
It was a problem in the call of an python script from c++. 
It fills up the storage. Bad python library. 

Mit freundlichen Grüßen 
Dr. Gert Taucher
