### ISSUE TITLE
How does cppflow use the faster-rcnn model？

### ISSUE THREAD

**Issue by swin223** [serizba/cppflow#162]
Hello, dear developer, 
As a beginner, I have a series of questions.
I am using [faster-rcnn](https://github.com/dBeker/Faster-RCNN-TensorFlow-Python3) recently.The faster rcnn 'env' is
~~~c
tensorflow-gpu 1.13.1
~~~
When I finish training the model, it will generate five files:
~~~c
checkpoint
faster_rcnn_iter_10000.ckpt.data-00000-of-00001
faster_rcnn_iter_10000.ckpt.index
faster_rcnn_iter_10000.ckpt.meta
faster_rcnn_iter_10000.pkl
~~~
I want to try to load these files into cppflow. What is the best way?
The .pb file was loaded in the cppflow example, but i didn't find it here.

**Comment by serizba** [comment]
Hi @swin223 

Those files are the saved weights of the model. But in cppflow you not only need the saved weights, you need the complete `saved_model` including the operations and the model architecture.

You can have a look to the `saved_model` format [here](https://www.tensorflow.org/guide/saved_model).

Hope it helps!
