### ISSUE TITLE
Proper syntax for loading a metagraph

### ISSUE THREAD

**Issue by JordanDavis-1** [serizba/cppflow#164]
Hello! First off I want to say that I am relatively new to Tensorflow but I am rapidly learning a lot. I currently have a project I'm trying to implement in C++ and thankful for stumbling upon cppflow. My understanding of C++ is also rusty but it's quickly coming back.

I am training a model in Python and would like to restore it for inference using cppflow within my app. It would be insightful if someone could help me reinterpret this python code below into how it could be loaded then ran using cppflow. The model is being restored from a checkpoint file.

```
_x = (np.random.rand(1, 100) * 2.) - 1.


x = graph.get_tensor_by_name('x:0')
D_z = graph.get_tensor_by_name('D_z:0')[:, :, 0]
_D_z = sess.run(G_z, {x: _x})
```
Any help would be appreciated and would help me move forward in my project and understanding!

**Comment by ljn917** [comment]
cppflow v1 loads ckpt file easier than v2. v2 currently only supports
loading SavedModel. I think there was a PR for adding ckpt file support
into v2 before.

**Comment by JordanDavis-1** [comment]
Thanks for your quick reply! Ahh that makes sense. I will downgrade to v1 then if that's the case. What would be the syntax for v1?

**Comment by ljn917** [comment]
https://github.com/serizba/cppflow/blob/c38997cbc2fdde9e77002c302d891cbd30ceab87/examples/mnist/main.cpp
