### ISSUE TITLE
how to resize a cppflow tensor

### ISSUE THREAD

**Issue by clelouch** [serizba/cppflow#167]
Thanks for your great work.
I implement a model, which takes a 128 * 128 image as input. However, I do not know how to resize the image. 
Could you please help me?

**Comment by serizba** [comment]
Hi!

If you already have the image as a `cppflow::tensor` you can resize it with `cppflow::resize_bicubic` (defined [here](https://github.com/serizba/cppflow/blob/883eb4c526979dae56f921571b1ab93df85a0a0d/include/cppflow/raw_ops.h#L17815)).

You can check the TensorFlow [raw operations](https://www.tensorflow.org/api_docs/python/tf/raw_ops/). Most of them should work in cppflow. The file with all of implemented functions is [here](https://github.com/serizba/cppflow/blob/master/include/cppflow/raw_ops.h).

**Comment by msj121** [comment]
Very rusty with c++, I have a 224x224 that I am trying to resize to 128x128. Currently I have:
```

auto input = cppflow::decode_jpeg(cppflow::read_file(std::string(filename)));
auto resized = cppflow::resize_bicubic(input,tensor({128,128}),true);
resized = cppflow::cast(resized, TF_UINT8, TF_FLOAT);
resized = input / 255.f;
resized = cppflow::expand_dims(input, 0);
```

However, I get the error:
`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: input must be 4-dimensional[224,224,3]`

Not sure how to turn this into a 4 dimensional array. It expects: ''images: 4-D with shape [batch, height, width, channels].''

Any help much appreciated.

**Comment by dskkato** [comment]
How about to call `expand_dims` before the resize operation?
```c++
auto input = cppflow::decode_jpeg(cppflow::read_file(std::string(filename)));
input = cppflow::expand_dims(input, 0);
auto resized = cppflow::resize_bicubic(input, tensor({128,128}),true);
resized = cppflow::cast(resized, TF_UINT8, TF_FLOAT);
resized = input / 255.f;

```

**Comment by msj121** [comment]
Awesome that compiled and ran. Now I need to figure out how to save the image to see what it looks like to make sure the resize works. Thanks!

**Comment by dskkato** [comment]
You can dump the resized image with the following ops: [EncdePng](https://www.tensorflow.org/api_docs/python/tf/raw_ops/EncodePng) and [WriteFile](https://www.tensorflow.org/api_docs/python/tf/raw_ops/WriteFile).

Before using `EncdePng`, you might need to cast and [Squueze](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Squeeze) the `resized` tensor to fit the above ops.

**Comment by serizba** [comment]
This looks fixed.
