### ISSUE TITLE
cpp::decode_video?

### ISSUE THREAD

**Issue by msj121** [serizba/cppflow#168]
I see there are a few different "decode" methods like "decode_png". Is there a way to run a cppflow model frame by frame using opencv on a video file/stream?

**Comment by ljn917** [comment]
Does tensorflow provide those ops? The `decode_*` ops are from tensorflow, e.g. <https://www.tensorflow.org/api_docs/python/tf/io/decode_png>

Otherwise, you need to convert the videos using OpenCV into the image formats that tensorflow supports.

**Comment by msj121** [comment]
Thanks - Don't see it there - will work to convert opencv to image formats and give that a try.
