### ISSUE TITLE
cannot force GPU utilization

### ISSUE THREAD

**Issue by sph001** [serizba/cppflow#179]
I have the below script which I am using to process 1080p video frames with a pretrained resnet50 model. while I expected this to process slowly, but I am only getting about 0.4 fps, which seems much slower than I expected. I have also noticed that the below code will not utilize my GPU and I cannot find a mechanism to attempt to force it to do so.

```cpp
std::vector<uchar> flatten(const cv::Mat* img){
    cv::Mat con;
    cv::cvtColor(*img, con, cv::COLOR_RGB2BGR);
    std::vector<uchar> flattened(img->rows * img->cols * img->channels());
    cv::Mat flat = con.reshape(1, con.rows * con.cols * con.channels());
    auto data = flat.ptr<uchar>();
    flattened.assign(data, data + flat.total() * flat.channels());
    return flattened;
}

int main(int argc, char** argv){
    std::vector<uint8_t> config{0x32,0xb,0x9,0x9a,0x99,0x99,0x99,0x99,0x99,0xd9,0x3f,0x20,0x1};
    TFE_ContextOptions* options = TFE_NewContextOptions();
    TFE_ContextOptionsSetConfig(options, config.data(), config.size(), cppflow::context::get_status());
    cppflow::get_global_context() = cppflow::context(options);
    cppflow::model model("/tmp/model/snapshot-100000.pb", cppflow::model::FROZEN_GRAPH);
    cppflow::tensor input;
    cv::VideoCapture capture("/tmp/model/camera_1.avi");
    while (count < 20){
        cv::Mat frame;
        capture >> frame;
        if (frame.empty())
            break;
        auto flat = flatten(&frame);
        input = cppflow::tensor(flat, {1080, 1920, 3});
        //std::cout << input.device(); returns CPU:0
        input = cppflow::cast(input, TF_UINT8, TF_FLOAT);
        input = cppflow::expand_dims(input, 0);
        auto output = model({{"Placeholder:0", input}},{"concat_1:0"});
    }
    return 0;
}
```

the only output I get from tensorflow is 
"2022-03-03 13:53:14.560098: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags."

have I configured something improperly to cause this or is this a limitation?

**Comment by serizba** [comment]
Hi @sph001 

Did you download the GPU version from the TensorFlow C API [site](https://www.tensorflow.org/install/lang_c)?

**Comment by sph001** [comment]
I did, but is there a way to validate that I have the right version (unfortunately system might have several versions from other users).

**Comment by serizba** [comment]
I am not an expert on CMake, but maybe you can try with
```
find_library(TENSORFLOW_LIB tensorflow HINT /path/to/mydir/lib)
```

And specify the location of your desired libtensorflow.

**Comment by sph001** [comment]
I have dumped out the linked libaray and it points to:
 ```
/usr/local/lib/libtensorflow.so
```
which is indeed where I installed it (and verified that there is only the gpu capable version there)

**Comment by serizba** [comment]
I see.

So, the only log you getting from TensorFlow is about oneAPI Deep Neural Network Library (oneDNN)? No other message from TensorFlow?

Does `nvidia-smi` work right and shows the available devices?

You can try to specify the device to use with:
```
CUDA_VISIBLE_DEVICES=0 ./my_executable
```

**Comment by sph001** [comment]
only get the oneDNN message

nvidia-smi gives the normal feedback (just for reference: NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6)

I have already exported CUDA_VISIBLE_DEVICES=0, added that anyway to the run and didn't get any difference in my run.

**Comment by serizba** [comment]
I am running out of ideas. I would carefully re-check that you are linking to the correct libtensorflow. Perhaps running the examples and manually setting the library paths so there is no way of opening the wrong library.

Sorry. Anyway, this looks like an issue with libtensorflow and not with cppflow.

**Comment by sph001** [comment]
no worries. thank you very much for your help.

**Comment by serizba** [comment]
If you find the problem write it here, in case someone encounters the same issue :)

**Comment by sph001** [comment]
closed
