### ISSUE TITLE
Cuda capabilities and cuda versions

### ISSUE THREAD

**Issue by paalpri** [serizba/cppflow#18]

**Comment by paalpri** [comment]
Hi! 
Seems like an awesome and easy module, and hope i get to use it, just running into a bit of problems when running your examples. 

Does this only work with CUDA toolkit 10.0 ? and a GPU with cuda capabilities of 6 ? 
I'm running into problems saying my GPU (which have cuda capabilities 5 ) is not high enough. 
Is there a way to solve this problem ? 

I also have to run on GPU, since my model that's built in python tensorflow requires a gpu to un on. 

Appreciate any help!

**Comment by serizba** [comment]
Hi!

Sorry for the late answer. Which CUDA toolkit and cuDNN version do you have?

**Comment by rodolfoap** [comment]
@paalpri I've got it running with the Cuda toolkit 10.0. I'm completely new on this domain, so I don't know what do you mean with "cuda capabilities of 6". I've installed Cudnn 7.6.4 from here: https://developer.nvidia.com/rdp/cudnn-archive, debian/buster, Nvidia driver from the apt repos.
