### ISSUE TITLE
How to create a two dimension tensor like (1000,5) (row,col)

### ISSUE THREAD

**Issue by fiveriddle** [serizba/cppflow#189]
I don't know whether I'm wrong or not, it seems that the cppflow::fill and cppflow::tensor can only support one dimension tensor in the example. 
If I'm wrong, could you please tell me where to or how to generate a 2d tensor like (1000,5) (row,col) and pass it into the model?
Many thanks!

**Comment by yochananscharf** [comment]
cppflow::tensor t = cppflow::fill({ 1000, 5 }, float(1));
