### ISSUE TITLE
Runtime_error

### ISSUE THREAD

**Issue by zhilee2019** [serizba/cppflow#20]
Thank you for your great cppLib! I came accross a problem. When I create Tensor like
auto input=new Tensor(model,"input"), a runtime error happened: no operation "input" exist. When I change to auto input=new Tensor(model,"ss") , an error : no operation "ss" happened. Do you know hwo to solve this question?

**Comment by Arnold1** [comment]
what is input? shouldn't that be a valid model, e.g. model.pb?
see:
https://github.com/serizba/cppflow/blob/master/examples/load_model/model.pb

**Comment by zhilee2019** [comment]
yeah, the model is a pb model. But, the model is trained by tensorflow 2.0, used the following project to transfer h5 file to pb file: https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py
Is that a problem?

**Comment by Arnold1** [comment]
The tf c libray here is 1.15 - they might not support all features. Can you check?

**Comment by serizba** [comment]
I am sorry, but CppFlow uses Tensorflow C API, and at the moment, the C API does not support officially TensorFlow 2.0

From TensorFlow C API [webpage](https://www.tensorflow.org/install/lang_c)

> Note: There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release.

**Comment by zhilee2019** [comment]
> The tf c libray here is 1.15 - they might not support all features. Can you check?

Thank you! I have transfered my model to tensorflow 1.13model, works perfectly

**Comment by zhilee2019** [comment]
> I am sorry, but CppFlow uses Tensorflow C API, and at the moment, the C API does not support officially TensorFlow 2.0
> 
> From TensorFlow C API [webpage](https://www.tensorflow.org/install/lang_c)
> 
> > Note: There is no libtensorflow support for TensorFlow 2 yet. It is expected in a future release.

Thank you for reply. The problem has been solved!
