### ISSUE TITLE
Memory leaks and memory management

### ISSUE THREAD

**Issue by lucadonati** [serizba/cppflow#21]
Why the 'new' s in the basic example?

Also I've some concerns about code like
`auto *dims = new int64_t[n_dims];`

I see no deletes for this

Of course I suppose you are aware that C++ is not garbage collected.

I've also seen malloc and delete[] mixed, I'm a bit concerned about the whole memory safety of the lib.

Could you please explain me a bit more about this?

**Comment by serizba** [comment]
I have recently merged the forked repo of @aul12 (thanks!), who saw some of these issues and improved the memory management. Nevertheless, if you detect further errors or leaks, feel free to open an issue or a pull request.
