### ISSUE TITLE
cppflow::read_file can"t load string

### ISSUE THREAD

**Issue by Whatsetsthisend** [serizba/cppflow#225]
Thank you for your great work, but I seem to have a little question day，
When i use:
cppflow::read_file((std::string)(ImagePath)),

i get this error:
Malformed TF_STRING tensor; element 0 out of range
i am sure my Imagepath is right
thank you

**Comment by serizba** [comment]
Hi,

I've never encountered such error. Could you provide a complete example to try to reproduce your problem?

Thanks!

**Comment by Whatsetsthisend** [comment]
I'm sorry I've solved this problem，it maked by version of Libtensorflow，use libtensorflow2.4.0 it will be fine
