### ISSUE TITLE
In and Output Conversion

### ISSUE THREAD

**Issue by vaan2010** [serizba/cppflow#23]
Hey there!

I converted a Keras model to a .pb file and tested it with python and everything works as expected. The input is a rgb image, every value is converted to a value between 0 and 1. The output is a black and white mask of that image.
When I tried different ways of doing this in Cpp with your coco example as a base I got a wide range of results but none of them make any sense to me. Do you have an example of loading the input of an rgb image and scaling the pixel values to 0-1? I'm not sure if the issue is how I convert Input, Output or both.

Best regards,
Vaan

**Comment by vaan2010** [comment]
Hey there!

I find solution of this problem by myself.
First, the images in sample code of coco were set to be uint_8, so if you wanna use your model was trained by python(float32), you have to change the input type and modify the code just like the following:

`       cv::Mat img, inp, inp2;
	img = cv::imread("Your Image", cv::IMREAD_COLOR);

	// resize and convert to float
	cv::resize(img, inp, cv::Size(62, 62));
	inp.convertTo(inp2, CV_32F, 1.0/255.0); //If your images need to be normalized
	cv::cvtColor(inp2, inp2, cv::COLOR_BGR2RGB); //If your images need to be converted to RGB

    //Turn uint_8 to float
	std::vector<float > img_data;
	img_data.assign((float*)inp2.data, (float*)inp2.data + inp2.total() * inp2.channels());`

Tha't all working!

**Comment by serizba** [comment]
Perfect!

Great that you realized of the solution and that now is working.

Now I will close the issue as it seems is solved.
