### ISSUE TITLE
tensorflow/c/c_api.h: No such file or directory

### ISSUE THREAD

**Issue by dhiegomaga** [serizba/cppflow#24]
Following the instructions inside **README**: 

> You can either install the library system wide by following the tutorial on the Tensorflow page **or you can place the contents of the archive in a folder called libtensorflow in the root directory of the repo**.

_(specifically, using the `libtensorflow` folder)_ I got the following error

`tensorflow/c/c_api.h: No such file or directory`

Which I expected; Nowhere **CMAKE** is informed of where this `libtensorflow` folder is, it makes sense it doesn't link to it. 

Do you know an easy way to fix this?  Also I'd say we need to add the locations of the *.so files from tensorflow, not only headers.

**Comment by serizba** [comment]
Thanks for posting the error and for the pull request.

I have the library installed system wide so I did not realize about the error.

Thanks!
