### ISSUE TITLE
Coco example

### ISSUE THREAD

**Issue by sunnyshh4ever** [serizba/cppflow#26]
Hi, may I know where to download the _frozen_inference_graph.pb in the Coco example? Thanks.

**Comment by serizba** [comment]
Sure!

If you look for "Coco tensorflow zoo" on a search engine you will find a [GitHub repo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) with different models. Once there you can download the one you want, although in the example I used _ssd_inception_v2_coco_. Also you can download the model directly from [here](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz).

Hope you find it!
