### ISSUE TITLE
Can this repo be used to load TF - Lite model?

### ISSUE THREAD

**Issue by harshgrovr** [serizba/cppflow#29]
I went through the examples. It was well explained. 

I wanted to ask if this git repo can be used to Tensorflow lite models too? In this git repo we are loading model graph and then loading weights before the inference. However, in Tensorflow lite we load the model using .tfLite file, like in the following example:

TF-lite:

https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_c

**Comment by serizba** [comment]
Hi!
I don't know too much about TF Lite but as far as I know the [TensorFlow C API](https://www.tensorflow.org/install/lang_c) in which this repo is based cannot be used to load TF Lite models.

I found that TensorFlow also has another [C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h) to work with TFLite. I haven't took a look on it but maybe is similar to the original one C API, and you can make a copy of this repository and change it for your needs. The other option will be to use TensorFlow for C++, but you will have to install and compile it.

Sorry and hope this helps you!
