### ISSUE TITLE
no such file or directory 

### ISSUE THREAD

**Issue by RofidaOsama7** [serizba/cppflow#31]
I'm using windows os , downloaded cppflow windows cpu only version from tensowrflow, unzip the file , and when trying to compile the code : 

#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}

it gave me this error 

![why](https://user-images.githubusercontent.com/58376958/84607973-71815580-aeb0-11ea-8e76-c832d8263f3c.JPG)

**Comment by dhiegomaga** [comment]
Did you download the tensorflow C API and extracted it inside a folder named `libtensorflow` in your home directoy? (or installed it system wide?) 

tensorflow C API: https://www.tensorflow.org/install/lang_c

**Comment by RofidaOsama7** [comment]
yes I downloaded it , extracted it in libtensorflow in the shown path (I think this the home directory for windows 10)
I put the hello_tf.c file in the cppflow folder just to try it 
 

![jw](https://user-images.githubusercontent.com/58376958/84716471-7824d100-af73-11ea-822e-ef8f16eede44.JPG)


I'm also asking about this error if you know when I tried to run the code in the README on cmd it gave me this error 
![jw2](https://user-images.githubusercontent.com/58376958/84716846-8e7f5c80-af74-11ea-8568-d56960bee35d.JPG)

**Comment by RofidaOsama7** [comment]
I read in one of the issues here that cmake files can fix such error so I tried 
but I'm little bit confused about the home directory  meaning in windows 10..
I downloaded your repo and directed it to this path 
C:\Users\20111\cppflow
and I copied libtensorflow folder inside cppflow, and in  C:\Users\20111 too 
I opened the cppflow folder in visual studio 2019 and I found these errors 
![vis](https://user-images.githubusercontent.com/58376958/84720872-8b3d9e00-af7f-11ea-9572-
19d742bf5d02.JPG)
the contents of the libtensorflow folder is like that 
![wwww](https://user-images.githubusercontent.com/58376958/84720961-c63fd180-af7f-11ea-85e5-80f92347cf68.JPG)

**Comment by dhiegomaga** [comment]
I'll assume you want to compile the examples. 
I'm not in windows and I'm not sure how those environment variables work there, but try doing the following: 
1. Open a terminal and type: `echo %userprofile%`. This should output a path to a folder, that should be your HOME folder
2. Put `libtensorflow` inside that folder
3. Change [this line](https://github.com/serizba/cppflow/blob/master/examples/mnist/CMakeLists.txt#L4) **on the examples (all of them)** to the following: 
```cmake
find_library(TENSORFLOW_LIB tensorflow HINT $ENV{HOME}/libtensorflow/lib $ENV{userprofile}/libtensorflow/lib)
```
4. Also change [this line](https://github.com/serizba/cppflow/blob/master/examples/mnist/CMakeLists.txt#L9) to:
```cmake
target_include_directories(example PRIVATE ../../include $ENV{HOME}/libtensorflow/include $ENV{userprofile}/libtensorflow/include )
```
Please let me know if it worked!

**Comment by RofidaOsama7** [comment]
thank you it worked and there was no error regarding generating files , all done 
but when I  typed make it gave me this error and as u can see there is no make file 

![no make](https://user-images.githubusercontent.com/58376958/84991084-5465b480-b146-11ea-9c05-ac110e91ea95.JPG)

(I ran make files on windows before and I'm sure it works)

I have a general question though and I'd really appreciate if you can help as I'm stuck for a while , 
I traind a VGG16 model in tensorflow , and I wanted to read the weights in every layer to use them with c++ functions that I coded myself 
the c++ code has some limitations to be synthesized with some tool 
for example the I have a convolution function that takes 3D array of the image[channels][size][size] , 4D array of the weights [number of filters][ number of channels][size of the filter][size of the filter] 
and 1d array of the filters biases and finally its output is a 3d array 
someone suggested cppflow to solve this problem and I was trying to run the examples and figure it out myself but I'm not sure how can cppflow help
can you please tell me how exactly and if you  by chance have another solution for my problem please help me.

**Comment by dhiegomaga** [comment]
I think this question fall a bit out of the scope of the thread... If you want to read the **weights** of the network, then cppflow wouldn't be so interesting, it would be much easier to do it in python. If you want to read the output of the forward pass through the network in C++ (in your case, the 3d array after the convolution), then you can use cppflow.
