### ISSUE TITLE
Runtime error after successful compile on example load_model

### ISSUE THREAD

**Issue by mfobert** [serizba/cppflow#33]
After following the instructions to load a model from the README, I can successfully compile the load_model example; however, when run, I receive a runtime error: Illegal instruction (core dumped)

I am running Ubuntu 19.10, GCC 9.2.1, the latest TensorFlow C API (libtensorflow-cpu-linux-x86_64-1.15.0).

Any tips on what I could be missing here? 

Thank you!

**Comment by dhiegomaga** [comment]
I haven't tried using g++9, can you try it using g++7, to eliminate that possibility?

**Comment by serizba** [comment]
I proceed to close the issue due to lack of activity
