### ISSUE TITLE
std::make_unique

### ISSUE THREAD

**Issue by fisakhan** [serizba/cppflow#34]
I receive the following two errors while running  mnist example using C++11 (cmake 3.10). Can you please help me solve this problem?

error: ‘make_unique’ is not a member of ‘std’
     this->actual_shape = std::make_unique<decltype(actual_shape)::element_type>(shape.begin(), shape.end());
                          
error: expected primary-expression before ‘>’ token
     this->actual_shape = std::make_unique<decltype(actual_shape)::element_type>(shape.begin(), shape.end());

**Comment by dhiegomaga** [comment]
https://stackoverflow.com/a/24609331/2076973

You should preferably compile using C++17

**Comment by jielyu** [comment]
add the following code in "Model.h", if you use c++11

```Cpp
namespace std {
    template<class T> struct _Unique_if {
        typedef unique_ptr<T> _Single_object;
    };

    template<class T> struct _Unique_if<T[]> {
        typedef unique_ptr<T[]> _Unknown_bound;
    };

    template<class T, size_t N> struct _Unique_if<T[N]> {
        typedef void _Known_bound;
    };

    template<class T, class... Args>
        typename _Unique_if<T>::_Single_object
        make_unique(Args&&... args) {
            return unique_ptr<T>(new T(std::forward<Args>(args)...));
        }

    template<class T>
        typename _Unique_if<T>::_Unknown_bound
        make_unique(size_t n) {
            typedef typename remove_extent<T>::type U;
            return unique_ptr<T>(new U[n]());
        }

    template<class T, class... Args>
        typename _Unique_if<T>::_Known_bound
        make_unique(Args&&...) = delete;
}
```

**Comment by serizba** [comment]
Hi @fisakhan,

Did you manage to solve your problem using C++ 17 or the workaround of @jielyu?

**Comment by fisakhan** [comment]
Yes
