### ISSUE TITLE
Question: How are multidimensional inputs/outputs handled?

### ISSUE THREAD

**Issue by TylerTheHumanCompiler** [serizba/cppflow#35]
From what I get .set_data() only takes a flat, 1-dimensional std::vector as input. If my model takes a 4-dimensional tensor as input with the shape (13. 84. 3. 5), how does it transform the flat std::vector into this shape?

Vice versa for output:
.get_data() return a flat vector. But what if my model outputs a multidimensional tensor, how will my data be ordered in this flat vector?

**Comment by dhiegomaga** [comment]
You should just convert from multiple dimensions to single dimensional, and back: https://colab.research.google.com/drive/14wky3FjyxUzvSEkmVCbzSLflxN252exe?usp=sharing

I'm not absolutely sure, but it should follow the convention of filling the dimension d0, then d1, then d2 ... on a [..., d2, d1, d0] tensor when getting it back to multiple dimensions. So if you just reshape the output vector from [1, 16380] to [13, 84, 3, 5], it should be in the right order.

**Comment by TylerTheHumanCompiler** [comment]
Thank you very much for your quick reply! I'm aware that this is not actually a bug or an issue, but simply a question, hence I'm really grateful.
Just to be sure, in case of my example above that would mean:
```
          [----------------------------------- d2 -----------------------------------]
          [--------- d1 ---------]  [--------- d1 ---------]  [--------- d1 ---------]
1D Array: [d0] [d0] [d0] [d0] [d0]  [d0] [d0] [d0] [d0] [d0]  [d0] [d0] [d0] [d0] [d0]
```

**Comment by serizba** [comment]
Exactly, it should follow that convention. Your example should be correct for a tensor with dimensions (1,3,5).

**Comment by andreykramer** [comment]
So I should change my model architecture and take only 1D inputs and produce 1D outputs? Doesn't vanilla tensorflow C api support multidimensional i/o?

**Comment by serizba** [comment]
Your model architecture is fine, it can take multidimensional inputs. The C API also supports multidimensional arrays, but c++ doesn't have multidimensional arrays in native form.

For this reason, with cppflow, you should create a flattened version of your data, a std::vector, and feed it to the tensors with set_data. Cppflow will convert them to the C API format, and they will be converted to their corresponding multidimensional tensor and given to your model.
