### ISSUE TITLE
Can not make example load_model (undefined reference to '_img__TF_')

### ISSUE THREAD

**Issue by McrBoot** [serizba/cppflow#37]
I ran in some issues following the 'How to run it" from this Github page. The Tensorflow C Api is placed into my home/libtensorflow and I'm running it on Windows 10 64bit.

To get the CMakeLists.txt to work I had to make some adjustments to it:
`cmake_minimum_required(VERSION 3.10)`
`set(CMAKE_C_COMPILER "gcc")`
`set(CMAKE_CXX_COMPILER "g++")`

`project(example)`

`find_library(TENSORFLOW_LIB tensorflow HINT "C:/Users/Menno/libtensorflow/lib")`

`set(CMAKE_CXX_STANDARD 17)`
`add_executable(example main.cpp ../../src/Model.cpp ../../src/Tensor.cpp)`
`target_include_directories(example PRIVATE ../../include "C:/Users/Menno/libtensorflow/include/")`
`target_link_libraries (example "${TENSORFLOW_LIB}")`

Also instead of calling `CMake ..` I had to use `CMake -G "Unix Makefiles" ..`

I've made a pastebin with all the output I'm getting: [https://pastebin.com/ijn0H9aJ](https://pastebin.com/ijn0H9aJ). In short it is a lot of errors with "undefined reference to '_imp__TF_X' where X stands for various TF components. 

I'm stuck right now and would really appreciate any help I can get.

**Comment by serizba** [comment]
Hi, 

Could you send the link of the libtensorflow binaries that you downloaded?

Thanks,
Sergio

**Comment by McrBoot** [comment]
Hello Sergio,

Thank you for your response. I used Windows CPU only from the "Install Tensorflow for C" link: 
Windows CPU only: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.15.0.zip

However I found another way to make Keras work so I no longer need cppflow.

Kind regards,

Menno
