### ISSUE TITLE
Is cppflow compatible with TensorFlow 2.2, and if so, how a model file should be created in TF2.2? 

### ISSUE THREAD

**Issue by rani-pinchuk** [serizba/cppflow#38]
Could you confirm that cppflow should work with TensorFlow 2.2?
And if so, could you provide an example of how to save a model so it works in TensorFlow 2.2? 

The reason I ask this is that I get "Invalid GraphDef" when trying to use a model.pb file created by model.save() of TF2.2.

Thanks,

Rani

**Comment by serizba** [comment]
Hi,

Currently cppflow is prepared to work with TF 1, and, although I am currently working on an improved version of it that adds some of the new features of TF 2, I don't know when I'll release the code. 

Regarding your problem, when you do `model.save()` you are saving a `SavedModel`, which includes a session, and therefore cannot be open with the previous methods. 
Luckily, you can use the code from the PR #27 , which adds this functionality. This PR even includes an example on how to load and run a saved model so it should be easy to reproduce.

Sergio

**Comment by CarlPoirier** [comment]
@rani-pinchuk I'm using cppflow PR #27 with libtensorflow version 2.3 which has been released days ago and it works.

You might need to check the input and output layer names again, as `model.save()` doesn't use the same ones as we had with the previous export methods. You can check the names with the [SavedModel CLI show](https://www.tensorflow.org/guide/saved_model#show_command) command.

Carl

**Comment by CarlPoirier** [comment]
@serizba How about first releasing the bare minimum to get the previous feature set running with the newer models? I'd like to use the upstream instead of a PR. ;)

**Comment by CarlPoirier** [comment]
@serizba Do you have any update about cppflow2 or whatever that you're going to call it ? Can I help with something?

**Comment by ljn917** [comment]
@serizba Glad to help too if it is possible.

**Comment by serizba** [comment]
Hi @CarlPoirier and  @ljn917,

I have upload what I have done until now of CppFlow 2 in a [new branch](https://github.com/serizba/cppflow/tree/cppflow2). It is not yet completed and it is not very well tested but it can serve as a minimum to work easily with TF2 and to perform tensor manipulation from C++.

I have included a README with some information on how is developed so you can tune it more easily for your needs.

**Comment by ljn917** [comment]
@serizba Great work. I will give it try when I have time. Thanks a lot.
