### ISSUE TITLE
C++ configuration

### ISSUE THREAD

**Issue by atlefk14** [serizba/cppflow#4]
Hi!

I was wondering if you can specify which version of C++ you are running, as I am having difficulties running the wrapper (complains about converting "Error	C2440	'return': cannot convert from 'T *' to 'std::vector<uint8_t,std::allocator<_Ty>>'"

**Comment by serizba** [comment]
I have tested with gcc version 7.4.0

**Comment by barisdemiray** [comment]
That must be the list initialization in Tensor::get_data(), https://github.com/serizba/cppflow/blob/master/src/Tensor.cpp#L146.

I had to replace,

    return {T_data, T_data + size};

with

    return std::vector<T>(T_data, T_data + size);

@serizba I'd call this change a step back caused by VS but tell me if you'd a like pull request. And thanks for the great work!

**Comment by serizba** [comment]
@barisdemiray Thanks for locating it! I think it would be nice to change it to add more support. So yes!

**Comment by barisdemiray** [comment]
Done, thanks.

**Comment by atlefk14** [comment]
It complains about "target_link_libraries (example -ltensorflow)" not being a valid configuration. The tensorflow api files are supposed to be under cppflow?

**Comment by CarlPoirier** [comment]
No, if you open the project properties, you will notice under Linker->Input->Additional Dependencies that cmake has added "-ltensorflow" as the GCC option. If you replace it with "tensorflow.lib" it will work as long as it's been configured to work.

I'm sure cmake can do it properly but I haven't looked into it myself.

**Comment by atlefk14** [comment]
Thanks. Another question tho, I would like to use a MaskRCNN network, which was trained in Python. Do I have to define all the different layers when loading the model, or is it enough with just loading the input and output layer?

**Comment by CarlPoirier** [comment]
Have a look at the wiki page. You create the model, you define the input and output tensors (visible layers only), you feed data, you run and then you get the results.
