### ISSUE TITLE
How  to call GPU to calculate?

### ISSUE THREAD

**Issue by ricolx** [serizba/cppflow#41]

**Comment by ricolx** [comment]
I successfully load model and predict the result in Cpp flow, but the Task manager showed it runs on CPU instead of  GPU. So it predicted slowly. Do you know any way to call GPU in Cpp flow? Thanks!

**Comment by srinivas1746** [comment]
I am also facing the same issue, Code is running on CPU instead of GPU. @ricolx can you help me out , if you solve it.
