### ISSUE TITLE
How to complete batch inference? 

### ISSUE THREAD

**Issue by bronstein87** [serizba/cppflow#43]
Hi. How can i complete batch inference? For example i have a model which input size is (?, 128, 64,3), so in python i can pass for example (8, 128, 64,3) or (16, 128, 64,3) using this code:
 
```
   input_var = tf.get_default_graph().get_tensor_by_name("images:0")
    output_var = tf.get_default_graph().get_tensor_by_name("features:0")
    val_x = []
     for filename in glob.glob(*.png"):
        print(filename)
        im = Image.open(filename)
        val_x.append(np.asarray(im))
    val_x_np = np.array(val_x)
    out = np.zeros((len(val_x_np), 128), np.float32)
    out = session.run(output_var, feed_dict={input_var: val_x_np})
```

but i can't understand how to do this using ccpflow... Could you explain, please?

**Comment by SRavit1** [comment]
Maybe it would help if you had a look at the coco example? https://github.com/serizba/cppflow/tree/master/examples/coco

As shown on this line (https://github.com/serizba/cppflow/blob/c38997cbc2fdde9e77002c302d891cbd30ceab87/examples/coco/main.cpp#L34):
    `inpName.set_data(img_data, {1, 300, 300, 3});`

All you need to do is set the tensor's values and shape. In this case, img_data is a vector of size 1*300*300*3=270,000.

If you want to run inference on multiple batches (given variable size input is supported by the model graph), you would need to have img_data be a vector of n*300*300*3 and a shape of {n, 300, 300, 3}.

Hope this helps! Good day.

**Comment by serizba** [comment]
Hi!

Yes, you can do it as pointed out by @SRavit1.

Did you manage to solve your problem @bronstein87?

**Comment by serizba** [comment]
I proceed to close the issue due to lack of activity
