### ISSUE TITLE
How to write the model.run section when the model got two images as inputs and one image as output?

### ISSUE THREAD

**Issue by demonstan** [serizba/cppflow#45]
This doesn't work.
```c++
Tensor inpName1{ model, "X1" };
Tensor inpName2{ model, "X2" };
Tensor outNames{ model, "Y" };

cv::Mat img1, inp1, img2, inp2;
img1 = cv::imread("img1.png", cv::IMREAD_COLOR);
img2 = cv::imread("img2.png", cv::IMREAD_COLOR);

std::vector<uint8_t > img1_data, img2_data;
img1_data.assign(img1.data, img1.data + img1.total() * img1.channels());
inpName1.set_data(img1_data, { 1, img_size, img_size, 3 });

img2_data.assign(img2.data, img2.data + img2.total() * img2.channels());
inpName2.set_data(img2_data, { 1, img_size, img_size, 3 });

model.run({inpName1, inpName2}, &outNames);
```

**Comment by serizba** [comment]
Hi!

What error are you getting? Could you provide a reproducible example? From this piece of code I cannot tell how is your used model.

Thanks!

**Comment by Kasthooriraja** [comment]
actual method
void Model::run(const std::vector<Tensor*> &inputs, Tensor &output) {
    this->run(inputs, &output);
}
so you need to pass the pointer of input tensors

try this
model.run({inpName1, inpName2}, &outNames); --> model.run({&inpName1, &inpName2}, outNames);

**Comment by serizba** [comment]
I proceed to close the issue due to lack of activity
