### ISSUE TITLE
Loading deepsort tensorflow model with cppflow

### ISSUE THREAD

**Issue by aditya-vora** [serizba/cppflow#47]
Hi, 

Thanks for this amazing work.

I compiled the cppflow library with visual studio and was able to run the example demo. As a next step, I was trying to load the tensorflow based deepsort model through cppflow.  The model files are available in this [repo](https://github.com/nwojke/deep_sort).  However, it seems I am getting an error in windows. Looks like cppflow is not able to load the model. Is it possible for you to help me in this regard?

Thanks, 
Aditya Vora

**Comment by aditya-vora** [comment]
Basically the issue is in the model.init() it is doing an error check whether init_op[0] is not NULL_PTR. It seems it is getting the null pointer in exception handling. Is it able to load the model correctly? I doubt it.

**Comment by aditya-vora** [comment]
@serizba is it possible for you to help me with this? I tried running model.get_operations() and replaced "init" with the first variable but doesn't seem to be working for me.

**Comment by ljn917** [comment]
It seems if you froze a graph so that there was no variable in it, there
would not be an init op.

Disclaimer: I have not read the source code to double check.

**Comment by aditya-vora** [comment]
Hi @ljn917, thanks for your response. I am using the same model available in the deepsort repo. I will share the [link](https://github.com/nwojke/deep_sort) to the repo for your reference. Also the [link](https://drive.google.com/drive/folders/18fKzfqnqhqW3s9zwsCbnVJ5XF2JFeqMp) to the drive where you can download the model. Using this model I am just trying to import the .pb files of this network using the cppflow.

**Comment by ljn917** [comment]
Did you try to run without calling init()? I saw other people doing this
with a frozen graph, and thus I had the previous speculation.

**Comment by ljn917** [comment]
https://github.com/aljabr0/from-keras-to-c/blob/master/model_run.cpp

This is the example I was talking about. What he/she had done is equivalent
to not call init_op in cppflow.

**Comment by aditya-vora** [comment]
Okay, let me try out this. Will get back to you. Thanks.
