### ISSUE TITLE
cppflow2: global context and status do not allow parallel execution with multiple threads

### ISSUE THREAD

**Issue by ljn917** [serizba/cppflow#52]
The current `context::get_status()` shares the same `TF_Status` in `context`, which cause a race condition if executed concurrently.

I am not sure about `TFE_Context` though. The header mentions some of its internal status are thread local.

One of the solutions is to use thread local context and status, e.g. as in [Swift](https://www.tensorflow.org/swift/api_docs/Structs/Context). (`thread_local` keyword in C++) I think this is the better solution.

The other solution is to allow users to create and manage their own context. We also need to keep the global default context for eager execution.

Edit:
The Context implementation in Swift API for tensorflow is [here](https://github.com/tensorflow/swift-apis/blob/master/Sources/TensorFlow/Context.swift). It uses a `ContextManager` (a stack of Context) to manage the default `Context` for the current thread and stores them in `ThreadLocalStorage`. I am not sure whether we need `ContextManager` or not, but it seems `thread_local` should also work for `Context`.

**Comment by serizba** [comment]
Yes, I didn't though about it for parallel execution.

For `TF_Status` using `thread_local` is a nice solution. I am also not sure about `TFE_Context` but it may also work.

**Comment by serizba** [comment]
Solved with #60
