### ISSUE TITLE
cppflow2: potential memory leak

### ISSUE THREAD

**Issue by ljn917** [serizba/cppflow#54]
The current implementation in `raw_ops.h` would leak `TFE_Op` (variable `op`) if `TFE_OpAddInput` or `TFE_Execute` failed and `status_check()` threw. One possible solution is to wrap `TFE_Op` with `unique_ptr`.

**Comment by serizba** [comment]
Yes, you are right, thanks for spotting it!

I will fix it

**Comment by serizba** [comment]
I added the `unique_ptr`
