### ISSUE TITLE
Documentation - HELP

### ISSUE THREAD

**Issue by JosipNizetic** [serizba/cppflow#55]
Hello,

I am sorry for bothering you but is there some more help documentation that you would suggest to use your code with following model.
[033_Hand_Detection_and_Tracking](https://github.com/PINTO0309/PINTO_model_zoo/tree/master/033_Hand_Detection_and_Tracking/01_float32)

and especially palm detection model that can be find here..
[saved_model_palm_detection_builtin](https://www.dropbox.com/s/xs8cqevwtz4uba0/saved_model_palm_detection_builtin.zip?dl=0)

I would like to implement TF .pb version and see speed difference in regards to already imeplented tflite. 

Thank you very much,
Josip

**Comment by serizba** [comment]
Hi,

I would like to add a bit of documentation, but right now is in an early state.

You should be able to load the .pb model with the new changes of [Cppflow2](https://github.com/serizba/cppflow/tree/cppflow2), you can take a look to the example on how to load a pb model and run it in the [examples folder](https://github.com/serizba/cppflow/tree/cppflow2/examples).

**Comment by JosipNizetic** [comment]
Ok thank you.

Tried that but had a bit trouble. Will try to dig deeper.


Best regards,
Josip

**Comment by serizba** [comment]
What did you tried and what are you trying to implement?

**Comment by ljn917** [comment]
Josip's models have multiple output tensors, which is not supported by v2
yet.

**Comment by JosipNizetic** [comment]
Thank you very much for clarification.

Josip

**Comment by ljn917** [comment]
@JosipNizetic One temporary workaround for this is using the v1 version in master branch and PR #27. However, the long term goal is to have SavedModel support in v2.

**Comment by serizba** [comment]
Hi @JosipNizetic,

I've created a function in model to work with multiple input/outpus, you can check an example on how it works on the [multi_input_output example](https://github.com/serizba/cppflow/tree/cppflow2/examples/multi_input_output).

You can now call your model with a list of tuples ("input_name", input_tensor) and a list of the names of the outputs. You can inspect the names of the model with the CLI tool provided by tensorflow:
`saved_model_cli show --dir path/to/model --all`

Then you can call your cppflow model like:

```[c++]
model({{"serving_default_input_1:0", input_1}, {"serving_default_input_2:0", input_2}}, {"StatefulPartitionedCall:0", "StatefulPartitionedCall:1"});
```

Note that you can specify the index of the operations after the colon `:`, as it is shown by `saved_model_cli`.

Hope it helps!

**Comment by ljn917** [comment]
@serizba Maybe using `std::unordered_map` as both inputs and outputs is easier to work with, instead of a vector of tuple, although there is greater overhead of constructing a hash table.

**Comment by JosipNizetic** [comment]
Thank you very much. Been out few days. Will try by tomorrow and get back..

Thank you once more..

**Comment by serizba** [comment]
Hi @JosipNizetic,

Did you manage to make it work?

**Comment by JosipNizetic** [comment]
Sorry for this vey long Delay. I thought i answered it. 
Yes everything is working fine..

Thank you very much.
