### ISSUE TITLE
Linking libraries on QT/IDE

### ISSUE THREAD

**Issue by aunsid** [serizba/cppflow#58]
Hey,

If I want to use this on an ide like QT, what should my lib path and linkers be? Thanks !

**Comment by serizba** [comment]
Hi,
I have never used QT, but for instance in CLion I just have to load the CMakeLists.txt as everything is detailed there.

If you do it manually, you need to tell the compiler where is your downloaded libtensorflow and where are the cppflow files.

**Comment by serizba** [comment]
I proceed to close the issue due to lack of activity
