### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by barrelo89** [serizba/cppflow#59]
Hello, 

I have been trying to test the examples, but every time I try 'make', I face such an error:

cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:79:23: error: expected unqualified-id before ‘[’ token
             const auto[op_name, op_idx] = parse_name(std::get<0>(inputs[i]));
                       ^
cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:80:68: error: ‘op_name’ was not declared in this scope
             inp_ops[i].oper = TF_GraphOperationByName(this->graph, op_name.c_str());
                                                                    ^~~~~~~
cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:81:32: error: ‘op_idx’ was not declared in this scope
             inp_ops[i].index = op_idx;
                                ^~~~~~
cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:96:23: error: expected unqualified-id before ‘[’ token
             const auto[op_name, op_idx] = parse_name(outputs[i]);
                       ^
cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:97:68: error: ‘op_name’ was not declared in this scope
             out_ops[i].oper = TF_GraphOperationByName(this->graph, op_name.c_str());
                                                                    ^~~~~~~
cppflow-cppflow2/examples/efficientnet/../../include/cppflow/model.h:98:32: error: ‘op_idx’ was not declared in this scope
             out_ops[i].index = op_idx;
                                ^~~~~~
CMakeFiles/example.dir/build.make:81: recipe for target 'CMakeFiles/example.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/example.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/example.dir/all' failed
make[1]: *** [CMakeFiles/example.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

It seems like there is no variable name after auto: const auto[op_name, op_idx] = parse_name(std::get<0>(inputs[i]));, and op_name and op_idx have not been created. 

Could any one give me some help on how to resolve this issue?

Thanks in advance.

**Comment by ljn917** [comment]
It seems your compiler does not support C++17. For structured binding, please refer to <https://en.cppreference.com/w/cpp/language/structured_binding>

**Comment by barrelo89** [comment]
After enabling C++17 in my compiler, It works like a charm.

Thanks for the help :)

**Comment by busyyang** [comment]
Is there a any way to make without C++17 support? My team wish our project can run in C++ 11.

**Comment by AlexanderEH** [comment]
I have the same issue, did you find a solution?

**Comment by serizba** [comment]
You can change the structured binding with a tuple, and then access the tuple elements.
