### ISSUE TITLE
Super Resolution Using cppflow 2

### ISSUE THREAD

**Issue by barrelo89** [serizba/cppflow#62]
Hello, 

First of all, I really appreciate your work that enables to use Tensorflow in C++ without bazel. 

I am using cppflow 2 to use the pre-trained super resolution model and output the SR images. 

Below is the code that I made for it:
`#include <iostream>
#include <typeinfo>
#include <opencv2/opencv.hpp>
#include <algorithm>
#include <iterator>
#include "../../include/cppflow/cppflow.h"

int main() {

    auto input = cppflow::decode_jpeg(cppflow::read_file(std::string("small.jpg")));
    input = cppflow::cast(input, TF_UINT8, TF_FLOAT);
    input = cppflow::expand_dims(input, 0);

    auto shape = input.shape().get_data<int>(); //num_data, height, width, num_channel;
    int num_row = shape[1];
    int num_col = shape[2];

    
    cppflow::model model("test_model");
    auto output = model(input);
    //output = cppflow::cast(output, TF_FLOAT, TF_UINT8);

    auto data = output.get_data<float>();
    std::cout << data.size() << std::endl;

    std::vector<uint8_t> sr_img;
    sr_img.assign(data.begin(), data.end());

    std::cout << sr_img.size()*sizeof(uint8_t) << std::endl;

    cv::Mat save = cv::Mat(num_row*4, num_col*4, CV_8UC3);

    memcpy(save.data, sr_img.data(), sr_img.size()*sizeof(uint8_t));

    //cv::cvtColor(save, save, cv::COLOR_RGB2BGR);
    cv::imwrite("result.png", save);
    //unsigned char* result = data.data();
    //stbi_write_png("sky.png", shape[2]*4, shape[1]*4, shape[3], result, shape[2]*4 * shape[3]);

    return 0;
}`

To load the input image, I used 'cppflow:decode_jpeg' function as in 'main.cpp' of efficientnet directory. 

After that, I load the pretrained SR model which was generated by this [link](https://github.com/barrelo89/CARN/blob/main/CARN.py), and ran the super resolution. 

The output from cppflow 2 was saved using opencv image write function (cv2::imwrite). 

However, the output from python code and the one from cppflow 2 are different!

[cppflow result](https://github.com/barrelo89/CARN/blob/main/cppflow.png)
[python3 result](https://github.com/barrelo89/CARN/blob/main/python.png)

I checked my SR model several times, but I don't think the model causes such inconsistency since it produces the same results in python.

Could anyone give me some guidance on why such difference happens?

Thanks in advance.

**Comment by ljn917** [comment]
Can you print out the elements of `input` and `output` tensors and compare them with the python input and output?

**Comment by barrelo89** [comment]
As you suggested, I first checked whether the elements of input tensors are the same as those in python. 

To cut straight to the conclusion, **IT IS DIFFERENT.**

Below is the input tensor created by "cppflow::decode_jpeg(cppflow::read_file(std::string("small.jpg")));"

(tensor: shape=[270 480 3], data=
[[[26 16 14]
  [19 8 4]
  [39 21 17]
  ...
  [96 54 30]
  [74 34 9]
  [60 23 0]]

 [[23 15 12]
  [19 10 5]
  [21 6 0]
  ...
  [48 10 0]
  [101 65 43]
  [113 79 54]]

 [[10 10 2]
  [19 17 5]
  [21 13 0]
  ...
  [40 9 0]
  [54 22 7]
  [70 41 25]]

 ...

 [[20 20 22]
  [19 19 21]
  [19 19 21]
  ...
  [21 21 23]
  [24 24 26]
  [21 21 23]]

 [[18 18 20]
  [21 21 23]
  [19 19 21]
  ...
  [19 19 21]
  [22 22 24]
  [21 21 23]]

 [[18 18 20]
  [23 23 25]
  [19 19 21]
  ...
  [19 19 21]
  [24 24 26]
  [25 25 27]]])

And this time, it is the input tensor from python (and I also tested in opencv c++, and it produced the same result):
array([[[ 20,  21,  31],
        [ 10,  12,  23],
        [ 20,  22,  40],
        ...,
        [ 32,  54,  96],
        [ 12,  34,  76],
        [  0,  22,  62]],

       [[ 17,  19,  27],
        [ 10,  12,  22],
        [  4,   9,  24],
        ...,
        [  0,   9,  50],
        [ 45,  64, 102],
        [ 57,  79, 115]],

       [[  7,  12,  13],
        [ 11,  20,  24],
        [  5,  15,  25],
        ...,
        [  0,   9,  42],
        [ 10,  23,  55],
        [ 30,  43,  75]],

       ...,

       [[ 23,  21,  21],
        [ 22,  20,  20],
        [ 21,  19,  19],
        ...,
        [ 24,  22,  22],
        [ 26,  24,  24],
        [ 23,  21,  21]],

       [[ 21,  19,  19],
        [ 24,  22,  22],
        [ 21,  19,  19],
        ...,
        [ 21,  19,  19],
        [ 25,  23,  23],
        [ 24,  22,  22]],

       [[ 21,  19,  19],
        [ 26,  24,  24],
        [ 22,  20,  20],
        ...,
        [ 22,  20,  20],
        [ 26,  24,  24],
        [ 27,  25,  25]]], dtype=uint8)

I figured out that "cppflow::decode_jpeg " function returns decoded image data in a different channel ordering (RGB) from opencv (BGR). 

So I re-trained my SR model by feeding input image data read via matplotlib.pyplot.imread, which read images in RGB ordering, and ran SR model in cppflow. 

Though the SR output looks much better, there still exists inconsistency in large number of pixel values. 
[cppflow](https://github.com/barrelo89/CARN/blob/main/cppflow_latest.png)
[python](https://github.com/barrelo89/CARN/blob/main/python_latest.png)

Revisiting the input tensor values by "cppflow::decode_jpeg ", the pixel values are different from those in python, regardless of opencv or matplotlib.

I guess such difference in input tensor values is causing the different output.

In this case, would there be a way that we just feed data into input tensor as in cppflow version 1?
Ex) input.set_data()

Thanks in advance.

**Comment by ljn917** [comment]
Did you try <https://www.tensorflow.org/api_docs/python/tf/io/decode_jpeg>?

You can also construct a tensor by <https://github.com/serizba/cppflow/blob/ff862943dc4167ee9a4bfb6ca5483cf0fbd201ce/include/cppflow/tensor.h#L35-L36>

**Comment by barrelo89** [comment]
'decode_jpeg' function in tensorflow indeed produced different pixel values!

Every guidance you @ljn917 provided led me some new finding! I really appreciate it!

To get the same pixel values as those from cv2.imread or plt.imread, I had to set the attribute dct_method to 'INTEGER_ACCURATE'  as mentioned in [link](https://stackoverflow.com/questions/45195880/why-does-tensorflow-decode-jpeg-images-differently-from-scipy-imread).

Below is the way to get the accurate pixel values: 
`
auto input = cppflow::decode_jpeg(cppflow::read_file(std::string("../small.jpg")), 0, 1, true, false, 1.0, std::string("INTEGER_ACCURATE"));
 `   
And I will also try the way to construct a tensor suggested above.

Thanks so much!

**Comment by ljn917** [comment]
Thanks for reporting back. It is also the first time I learn `decode_jpeg` produces different results than other implementation!

**Comment by serizba** [comment]
I didn't expect that, thanks for pointing it!

@barrelo89 , should we close the issue now that you figured out the origin of the different output?

**Comment by barrelo89** [comment]
Sure. I will close it.
