### ISSUE TITLE
Memory leak question

### ISSUE THREAD

**Issue by karloballa** [serizba/cppflow#70]
I have this simple (pointless) loop:

auto input = cppflow::tensor(inData, shape);
for (size_t i = 0; i < 50000; i++)
  auto res = model(input);

It eats memory in every iteration. It seems that in every iteration it makes 2 additional allocations. I'm not sure where I'm wrong.

Thanks,

**Comment by karloballa** [comment]
After about 20000 forward steps the net eats more than half GB of the heap.
Any opinions?

![cppflow1](https://user-images.githubusercontent.com/45897907/99855447-2ff38580-2b87-11eb-948a-6de44f5116c7.png)
![cppflow2](https://user-images.githubusercontent.com/45897907/99855459-35e96680-2b87-11eb-9f79-729433a2e798.png)

**Comment by serizba** [comment]
Hi @karloballa,

As others have pointed (#69) there is a leak in the call operator. It may be the source of your problem. You can check the PR where there is a proposal to fix it. At the moment we are working to merge the changes.

Thanks

**Comment by shyney7** [comment]
@karloballa this should be fixed since #69 was merged. At least into the cppflow2 branch. Can you confirm this and close this issue if its fixed?

**Comment by karloballa** [comment]
It is ok now. Thanks!
