### ISSUE TITLE
cppflow(1) output.get_data<float>(); 

### ISSUE THREAD

**Issue by OfekShochat** [serizba/cppflow#79]
I am trying to run predictions and I am trying to convert the output Tensor type to float. but it doesn't work. 
why?
```
float Net::predict(string fen) {
        Tensor input{ model, "input" };
	Tensor output{ model, "output" };
	list<list<float>> d = make(fen);
	vector<list<list<float>>> result(d.size());
	copy(d.begin(), d.end(), result.begin());
	input.set_data(result);
	model.run(input, output);
	return output.get_data<float>();
}
``` 
Note that it converts this to vector<float, allocator<float>> instead of float. do I need to just convert it to float then?
and also tried to convert to double but from this vector but with no luck.

**Comment by serizba** [comment]
Hi @OfekShochat ,

Can you add a minimum example that we could be able to run? What error are you getting?

If `output` contains just a scalar, then I guess you just need to take the first value of the returned vector:
```c++
return output.get_data<float>()[0]
```

**Comment by OfekShochat** [comment]
sure, that makes an error: "binary '=' no operator found wich takes a right-hand ...". 

*.h:
```
#pragma once
#include "neural/tensorflow/Model.h"
#include "neural/tensorflow/Tensor.h"
#include <iostream>
#include <list>
#include <string>

using namespace std;

class Net {
public:
	Net(string path);

	float predict(string fen);
private:
	Model model;

	list<list<float>> make(string fen);
};
```
*.cpp:
```
#include "neural/tensorflow/use.h"
#include "neural/tensorflow/Tensor.h"
#include "neural/tensorflow/Model.h"
#include "chess/thc.h"
#include <iostream>
#include <list>
#include <string>
#include <vector>

using namespace std;

Net::Net(string path) : model(path) {
	model.init();
}

list<list<float>> Net::make(string fen) {
	list<list<float>> b;
	list<float> tb;
	const char* c = fen.c_str();
	thc::ChessRules cr;
	cr.Forsyth(c);
	string s = cr.ToDebugStr();

	for (auto piece = s.cbegin(); piece != s.cend(); ++piece) {
		switch (*piece) {
		case 'R' : 
			tb.push_back(5.0);
			break;
		case 'N' : 
			tb.push_back(3.2);
			break;
		case 'B' : 
			tb.push_back(3.4);
			break;
		case 'Q' : 
			tb.push_back(9.0);
			break;
		case 'K' : 
			tb.push_back(200.0);
			break;
		
		case 'r' : 
			tb.push_back(-5.0);
			break;
		case 'n' : 
			tb.push_back(-3.2);
			break;
		case 'b' :
			tb.push_back(-3.4);
			break;
		case 'q' :
			tb.push_back(-9.0);
			break;
		case 'k' :
			tb.push_back(-200.0);
			break;
		case '\n':
			b.push_back(tb);
			tb.clear();
			break;
		}
	}
}

float Net::predict(string fen) {
	Tensor input{ model, "input" };
	Tensor output{ model, "output" };
	list<list<float>> d = make(fen);
	vector<list<list<float>>> result(d.size());
	copy(d.begin(), d.end(), result.begin());
	input.set_data(result);
	model.run(input, output);

	return output.get_data<float>()[0];
}
```

**Comment by serizba** [comment]
@OfekShochat 

So, even accessing the vector with `return output.get_data<float>()[0];``you get the same error? Can you write the full output of the error? In which line exactly does it fail?

**Comment by OfekShochat** [comment]
yes. the error is this: 
C2679	binary '=': no operator found which takes a right-hand operand of type 'std::list<float,std::allocator<float>>' (or there Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xutility	line 4142

**Comment by serizba** [comment]
@OfekShochat 

But I guess that's not the full error trace. The full error trace should show more information about the location and the calling stack of the error. 

Also, `set_data(std::vector<T> new_data)` is expecting `T` to be a primitive type, like `float`, `ìnt`... you are passing it a `vector<list<list<float>>>` and therefore `T` is `list<list<float>>`. You should flat your data before passing it to to `set_data()`. That is, `result` should be a `vector<float>`.

**Comment by OfekShochat** [comment]
I used keras conv2d net. so do I need to flatten it?

**Comment by serizba** [comment]
@OfekShochat 

Yes, the data should be flattened before setting it. That doesn't mean that the tensor should be flat, but to read the data from c++, it should receive a flat `std::vector`. If the tensor is not flat (like an image for your conv2d), you have to pass it as a flat vector, and specify the shape. For instance, you can see the [coco example](https://github.com/serizba/cppflow/blob/243ff2fc4e33632b91676cad7d6cfc3c92308601/examples/coco/main.cpp#L31):
```c++
    // Put image in Tensor
    std::vector<uint8_t > img_data; // This is a flat vector
    img_data.assign(inp.data, inp.data + inp.total() * inp.channels()); // Fill the flat std::vector with data
    inpName.set_data(img_data, {1, 300, 300, 3}); // Assign the data to the tensor, and specify the shape
```

**Comment by OfekShochat** [comment]
what is inp.data?

**Comment by serizba** [comment]
@OfekShochat 

Is a opencv matrix. It is not relevant. In that line we are only filling the `img_data` vector.

**Comment by OfekShochat** [comment]
just what is the input? the output from the `make()` function?

**Comment by serizba** [comment]
@OfekShochat 

There is an image stored in `inp`. 

I think that in your case the image is in `d`, and you should traverse that list of lists and write its data into the flat version of `result`.

**Comment by OfekShochat** [comment]
im sorry for my ignorance, but total is just the size? that's not true I know. but what is the total?

**Comment by serizba** [comment]
@OfekShochat 

`inp` is a matrix (h x w x c), `inp.data()` points to the raw data, `inp.total()'` is number of elements (h x w) and `inp.channels()` is number of channels (c). But, if you are not using opencv, you don't need to care about this, you just need to fill your `vector` with your data, with a for loop, or the way you prefer.

**Comment by OfekShochat** [comment]
so should I just make the `make` function make 1D arrays and then let the lib slice it with the shape?

**Comment by serizba** [comment]
@OfekShochat 

Yes, you can make a 1D vector, and specify the shape on `set_data`.

**Comment by OfekShochat** [comment]
sorry for the wait, I was sleeping. now it is linking problems. probably something in my code do you have a guess?

**Comment by serizba** [comment]
@OfekShochat 

Without posting the linking errors is difficult that I can have a guess

**Comment by OfekShochat** [comment]
sorry about that.
[errors (2).txt](https://github.com/serizba/cppflow/files/5627751/errors.2.txt)

**Comment by serizba** [comment]
@OfekShochat 

Looks like is not linking correctly the TF C API. Did you install the TF C API in your system? Have you tried to compile and run a small program to check if the installation was successful?

**Comment by OfekShochat** [comment]
I downloaded the tf zip from https://www.tensorflow.org/install/lang_c and put it on the directory of the c_api and changed the include from <> to the dir of the files. so should I run your example and see?

**Comment by serizba** [comment]
@OfekShochat 

Yes, running one of the examples is a nice way of checking it. Did you place it in a folder named `libtensorflow` in your `$HOME` directory? If not, you should place it there, or install it system wide, or specify where is it in your `CMakeLists.txt`. You can check [this guide to install it](https://serizba.github.io/cppflow/installation.html), although is for cppflow2, it also works for cppflow1.

Btw, how are you compiling your code? Are you using one of the provided `CMakeLists.txt`? If not, perhaps you are not even linking it.

**Comment by OfekShochat** [comment]
I specified the dir of the dll to vs

**Comment by serizba** [comment]
@OfekShochat 

I am not used to vs, so I am not sure, but you should try to compile one of the smaller example programs.

**Comment by OfekShochat** [comment]
the load_model project outputs the same error.

**Comment by serizba** [comment]
@OfekShochat 

For the load model example did you use the provided CMakeLists.txt or did you link it with vs?

**Comment by OfekShochat** [comment]
vs

**Comment by serizba** [comment]
@OfekShochat 

Then probably you are linking something wrong. Try to mimic the CMakeLists.txt behavior.

**Comment by OfekShochat** [comment]
I do the same thing. I include the dll dir in the link phase, I include the tensorflow, so what could go wrong?

**Comment by serizba** [comment]
@OfekShochat 

I run out of idea. But I encourage you to use the CMakeLists.txt

**Comment by OfekShochat** [comment]
it was the dll file.
