### ISSUE TITLE
visual studio for generated lib porblem 

### ISSUE THREAD

**Issue by zhwj888** [serizba/cppflow#87]
Hi serizba, thanks for your wounderful job.
It is ok to use cppflow2 to load the savedmodel and show the predication result from visual studio c++ generated **exe** file.
But, I met a problem after I turned the cpp file into dll and lib and made the implicit invocation of them. 
The console got stuck after showing  **Successfully opened dynamic library cudart64_101.dll**. Could you please help me to solve the problem? Thank you.

**Comment by ljn917** [comment]
Can you try to wrap <https://github.com/serizba/cppflow/blob/dbca38ce06b606fde80a3c7f3293e7694316ab71/include/cppflow/context.h#L44> into a function?

```
// untested
inline context* get_global_context() {
static context global_context;
return &global_context;
}
```

**Comment by zhwj888** [comment]
@ljn917 
Thanks for your reply.
But unfortunately, with adding the code you provided, the dll and lib cant be generated.
To be more specific to my original question, here is a screenshot of the implicit invocation result:
![githubcppflow](https://user-images.githubusercontent.com/12584378/102796356-185b2700-43e9-11eb-8433-46f81384dffc.PNG)

Here is the modified context.h code:
`
..........code
namespace cppflow {

    inline bool status_check(TF_Status* status) {
        if (TF_GetCode(status) != TF_OK) {
            throw std::runtime_error(TF_Message(status));
        }
        return true;
    }

    class context {
        public:
            static TFE_Context* get_context();
            static TF_Status* get_status();

        private:
            TFE_Context* tfe_context{nullptr};

        public:
            explicit context(TFE_ContextOptions* opts = nullptr);

            context(context const&) = delete;
            context& operator=(context const&) = delete;
            context(context&&) noexcept;
            context& operator=(context&&) noexcept;

            ~context();
    };

    // TODO: create ContextManager class if needed
    inline context* get_global_context() {
        static context global_context;
        return &global_context;
    }
}
...............

`

**Comment by ljn917** [comment]
You also need to modify all the references to `global_context` to `get_global_context()->...`. I think the only place to change is line 51.

**Comment by ljn917** [comment]
@zhwj888 Can you test PR #88?

**Comment by zhwj888** [comment]
@ljn917  
Just did the same thing as your sample modification. But failed to generate lib and dll file.

**Comment by ljn917** [comment]
@zhwj888 Do you mean PR #88?

**Comment by zhwj888** [comment]
@ljn917 
Yes.
![githubcpp](https://user-images.githubusercontent.com/12584378/102807120-10a37e80-43f9-11eb-9f22-e6f82ee9725c.PNG)

**Comment by ljn917** [comment]
@zhwj888  What is the error message? Note that PR #88 and the sample code I sent before are different.

**Comment by zhwj888** [comment]
@ljn917 
Yes, my change is the same.
And I need to download the language pack, since the errors which are related to context.h are many.

**Comment by ljn917** [comment]
It is wired. I got no issue with gcc.

Can you try to compile one of the examples with PR #88 first? Thanks.

**Comment by zhwj888** [comment]
@ljn917 
Some of the errors:
 ```
'TFE_Context *cppflow::context::get_context(void)': symbol cannot be defined within namespace 'cppflow'
error C2888: 'TF_Status *cppflow::context::get_status(void)': symbol cannot be defined within namespace 'cppflow'
error C2888: 'cppflow::context::context(TFE_ContextOptions *)': symbol cannot be defined within namespace 'cppflow'
error C2065: 'get_status': undeclared identifier
error C2664: 'TFE_Context *TFE_NewContext(const TFE_ContextOptions *,TF_Status *)': cannot convert argument 2 from 'TF_Status *(__cdecl *)(void)' to 'TF_Status *'
There is no context in which this conversion is possible
```
Of course, I m gonna try the example.

**Comment by zhwj888** [comment]
@ljn917 
got same errors from tensor example

**Comment by ljn917** [comment]
@zhwj888 Is it possible to post all the error messages?

**Comment by zhwj888** [comment]
@ljn917 
`E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(51,48): error C2888: 'TFE_Context *cppflow::context::get_context(void)': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(55,45): error C2888: 'TF_Status *cppflow::context::get_status(void)': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(60,55): error C2888: 'cppflow::context::context(TFE_ContextOptions *)': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(61,35): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(64,69): error C2664: 'TFE_Context *TFE_NewContext(const TFE_ContextOptions *,TF_Status *)': cannot convert argument 2 from 'TF_Status *(__cdecl *)(void)' to 'TF_Status *'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(64,60): message : There is no context in which this conversion is possible
1>D:\libtensorflow-gpu-windows-x86_64-2.3.0\include\tensorflow/c/eager/c_api.h(99,36): message : see declaration of 'TFE_NewContext'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(66,63): error C2664: 'TFE_Context *TFE_NewContext(const TFE_ContextOptions *,TF_Status *)': cannot convert argument 2 from 'TF_Status *(__cdecl *)(void)' to 'TF_Status *'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(66,54): message : There is no context in which this conversion is possible
1>D:\libtensorflow-gpu-windows-x86_64-2.3.0\include\tensorflow/c/eager/c_api.h(99,36): message : see declaration of 'TFE_NewContext'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(68,31): error C2664: 'bool cppflow::status_check(TF_Status *)': cannot convert argument 1 from 'TF_Status *(__cdecl *)(void)' to 'TF_Status *'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(68,22): message : There is no context in which this conversion is possible
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(17,17): message : see declaration of 'cppflow::status_check'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(71,53): error C2888: 'cppflow::context::context(cppflow::context &&) noexcept': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(76,64): error C2888: 'cppflow::context &cppflow::context::operator =(cppflow::context &&) noexcept': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\context.h(81,32): error C2888: 'cppflow::context::~context(void)': symbol cannot be defined within namespace 'cppflow'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(133,83): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(135,81): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(135,118): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\memory(1183,17): message : could be 'std::shared_ptr<TFE_TensorHandle> &std::shared_ptr<TFE_TensorHandle>::operator =(std::shared_ptr<TFE_TensorHandle> &&) noexcept'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\memory(1172,17): message : or       'std::shared_ptr<TFE_TensorHandle> &std::shared_ptr<TFE_TensorHandle>::operator =(const std::shared_ptr<TFE_TensorHandle> &) noexcept'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(135,118): message : while trying to match the argument list '(std::shared_ptr<TFE_TensorHandle>, initializer list)'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(136,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(167,83): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(168,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(181,81): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(181,118): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(181,118): message : while trying to match the argument list '(std::shared_ptr<TFE_TensorHandle>, initializer list)'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(182,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(186,38): error C2065: 'get_context': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(186,71): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(187,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(189,26): error C3536: 'op': cannot be used before it is initialized
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(189,61): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(190,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(195,43): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(196,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(197,24): error C2664: 'void TFE_DeleteOp(TFE_Op *)': cannot convert argument 1 from 'int' to 'TFE_Op *'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(197,22): message : Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
1>D:\libtensorflow-gpu-windows-x86_64-2.3.0\include\tensorflow/c/eager/c_api.h(252,28): message : see declaration of 'TFE_DeleteOp'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(205,86): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(207,91): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(209,31): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(237,77): error C2065: 'get_status': undeclared identifier
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(237,107): error C2679: binary '=': no operator found which takes a right-hand operand of type 'initializer list' (or there is no acceptable conversion)
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(237,107): message : while trying to match the argument list '(std::shared_ptr<TF_Tensor>, initializer list)'
1>E:\cppflow-cppflow2\cppflow-cppflow2\include\cppflow\tensor.h(238,35): error C2065: 'get_status': undeclared identifier`

**Comment by ljn917** [comment]
Can you try to merge the two `cppflow` namespace into one?

**Comment by zhwj888** [comment]
@ljn917 

It is weird, after the change #include <iostream> can not work with message:**_There are too many errors for the IntelliSense engine to function correctly_**

**Comment by ljn917** [comment]
I never used IntelliSense.... so I cannot help here. I tried to compile the code with both gcc 10 and clang 11 under linux, and there was no error.

Can you try a newer version or a different version of VS?

**Comment by zhwj888** [comment]
@ljn917 
Thanks for your patience.
Well, the strange thing is I commented off the #include ** cppflow/ops.h**, IntelliSense errors dissappeared. But, all the cppflow2 functions are labeled by red wave lines even with #include **cppflow/cppflow.h**.

**Comment by ljn917** [comment]
Maybe ignore IntelliSense errors and try to compile directly?

**Comment by zhwj888** [comment]
@ljn917 
Nah, failed, too many MSVC error reports.....
Gonna make a try to fix it tommorrow. 
Once the problems got fixed, I will make the reply.
Anyway, cppflow2 is a wonderful library!

**Comment by zhwj888** [comment]
@ljn917 
I fixed the problem，now it works fine
Its my problem indeed， I forgot to put "}" after merging of namesapace.
Thanks for the help.

**Comment by ljn917** [comment]
@zhwj888 Good to know it works.

Can you do me a favor and also test pr #88 without any changes? Thanks.

**Comment by zhwj888** [comment]
@ljn917 
No problem, glad I can do some contribution to this marvelous project.
Gonna test it tommorow morning.
By the way, just want to make sure, do you mean the file with **Avoid variable shadowing**?

**Comment by ljn917** [comment]
@zhwj888 Yes. I just want to make the pr can be compiled correctly on windows. In my opinion, merging cppflow namespace should not be necessary.

**Comment by zhwj888** [comment]
@ljn917 
Ok, I tested it, it works fine.

**Comment by ljn917** [comment]
@zhwj888 Thanks a lota
