### ISSUE TITLE
Shape is int32_t instead of int64_t

### ISSUE THREAD

**Issue by bytosaur** [serizba/cppflow#91]
Hey everyone,

i noticed when asking for the shape of a tensor I receive wrong values. One constructor says to feed in the shape as std::vector<int64_t>, which may be fine. But when receiving a shape I need to cast to int32_t!
```c++ 
auto tensor = cppflow::fill({1, 2, 2, 3}, 0.9f);
auto shape_wrong = tensor.shape().get_data<int64_t>(); // contains wrong values
auto shape_corrct = tensor.shape().get_data<int32_t>(); // contains correct values
```

I recommend to use the following constructor which may not lead to confusion:
```c++
template<typename T>
tensor(const std::vector<T>& values, const std::vector<int32_t>& shape);
```
Also consider to add a get_shape() function which returns the shape as a std::vector<int32_t>.

**Comment by serizba** [comment]
Hi @bytosaur ,

Thanks for pointing this,

I didn't realize that `tf.raw_ops.Shape` returns an `int32_t` tensor by default. I should specify to return a `int64_t` to be consistent.
I think is better to change the `shape` function, as changing the constructor would then require to cast the values to `int64_t` because that is the expected input of 

```c++
TF_AllocateTensor(TF_DataType, const int64_t* dims, int num_dims, size_t len)
```

Thanks!

**Comment by bytosaur** [comment]
hey @serizba,

thank you for making this repository, you are doing a great job! We have used it to make an addon for openFrameworks https://github.com/zkmkarlsruhe/ofxTensorFlow2

In this project we stuck to the int64_t and convert the output of shape():
```c++
cppflow::cast(tensor.shape(), TF_INT32, TF_INT64).get_data<int64_t>();
```

**Comment by ljn917** [comment]
It may be off topic. Is there any possibility to place some runtime check
such that only the right get_data<T>() is called?

**Comment by serizba** [comment]
Hi @bytosaur 

Now we specifically ask for int64_t in tensor::shape(), so the problem should be solved.
Thanks for your message. By the way, the project you are working on looks very interesting, good luck with it!

**Comment by serizba** [comment]
@ljn917 

Good suggestion, thanks!

I have included a runtime check of the datatype such that it throws an error if the function `get_data<T>()` is invoked asking for a datatype different from the tensor type.
