### ISSUE TITLE
Can I compute gradient of the model output w.r.t input?

### ISSUE THREAD

**Issue by junhyeokahn** [serizba/cppflow#92]
Hello,
First of all, I appreciate your effort to maintain this nice repo.
I am wondering if I can get a gradient of the network model output w.r.t input similar to [this function](https://www.tensorflow.org/api_docs/python/tf/GradientTape?hl=zh-cn) in ```tensorflow```.

**Comment by serizba** [comment]
Hi @junhyeokahn 

This repo was intended to perform inference in C++. There are some functions in the TF C API that helps into obtaining gradients, but there is no plan to introduce them in this library.

If someone knows how to do this with the current implementation, he can post it here.
