### ISSUE TITLE
cppflow2 : Getting model input and output size

### ISSUE THREAD

**Issue by CarlPoirier** [serizba/cppflow#94]
Hi,

In cppflow 1, we could get the model input shape by doing the following:
`auto input_shape = Tensor(MyModel, "input_1").get_shape();`

I did not find an equivalent in cppflow2. Is there one I missed?

Carl

**Comment by serizba** [comment]
Hi @CarlPoirier ,

Sorry, but right now there is nothing like this. Nevertheless, you can easily implement this behavior by taking  a look to the cppflow1 implementation of Tensor:

```c++
Tensor::Tensor(const Model& model, const std::string& operation) {

    // Get operation by the name
    this->op.oper = TF_GraphOperationByName(model.graph, operation.c_str());
    this->op.index = 0;

    // Operation did not exists
    error_check(this->op.oper != nullptr, "No operation named \"" + operation + "\" exists" );

    // DIMENSIONS

    // Get number of dimensions
    int n_dims = TF_GraphGetTensorNumDims(model.graph, this->op, model.status);

    // DataType
    this->type = TF_OperationOutputType(this->op);

    // If is not a scalar
    if (n_dims > 0) {
        // Get dimensions
        auto *dims = new int64_t[n_dims];
        TF_GraphGetTensorShape(model.graph, this->op, dims, n_dims, model.status);

        // Check error on Model Status
        model.status_check(true);

        this->shape = std::vector<int64_t>(dims, dims + n_dims);

        // Only one dimension can be unknown using this constructor
        // error_check(std::count(this->shape.begin(), this->shape.end(), -1) <= 1, "At most one dimension can be unknown");

        delete[] dims;
    }

    this->flag = 0;
    this->val = nullptr;
    this->data = nullptr;
}
```

In the previous code is relatively simple to see how to fill the shape value. You can implement a similar function in cppflow2::model that takes a string (operation name) as input and returns the shape.

Hope it helps

**Comment by CarlPoirier** [comment]
Hi Sergio,

Thanks for your reply. Here is a pull request for the discussed functionality. If there is anything I can do to make it better, let me know.

Carl

**Comment by serizba** [comment]
Great, thanks!
